#!/bin/sh

. /usr/share/libubox/jshn.sh
. /lib/functions.sh

UpdateConfigScript="/root/InterfaceManager/script/ospfstatus.sh"

case "$1" in
    list)
        echo '{"configure":{"application":"ApplicationName","action":"ActionName"}}'
        ;;
    call)
        case "$2" in
                   configure)
		                # read the arguments
		                echo "{\"code\":\"0\",\"output\":\"Updated OSPF Status\"}"  
		                response=$(sh $UpdateConfigScript)
		                RetVal=$?
		                echo "{\"code\":\"0\",\"output\":\"Updated OSPF Status\"}"                                   
		                ;;
		                                   
                    *)
                    echo '{"code":"1","output":"invalid method"}'
                    exit 1
        esac #appmanager method
            ;;
esac # ubus method

exit 0
