#!/bin/sh

. /usr/share/libubox/jshn.sh
. /lib/functions.sh

smartsqm="/etc/init.d/sqm restart"

case "$1" in
    list)
        echo '{"smartsqm":{},}'
        ;;
    call)
    
        case "$2" in
        
                      smartsqm)
                             
                            response=$($smartsqm)
							if [ "$?" -ne 0 ]
                            then
								echo "{\"code\":1,\"output\":\"FAILURE : SQM Configuration Update\"}"
                            else
                               	echo "{\"code\":0,\"output\":\"SUCCESS : SQM Configuration Update\"}"
                            fi
                                                                                 
                            ;; 
                   
						
                
		             *)
		                    echo '{"code":"1","output":"invalid method"}'
		                    exit 1
		                    ;;
     
        esac #appmanager method
        ;;
esac # ubus method

exit 0
