#!/bin/sh

. /usr/share/libubox/jshn.sh
. /lib/functions.sh

UpdateConfigScript="/bin/QueryModemStatus.sh"

case "$1" in
    list)
        echo '{"configure":{}}'
        ;;
    call)
        case "$2" in
                    configure)
                            file=$(cat /tmp/ModemAnalytics1.txt) 
                            file2=$(cat /tmp/ModemAnalytics2.txt) 
                         	echo "{\"code\":0,\"output\":\"$file\"}"                                                                        
                         	echo "{\"code\":0,\"output\":\"$file2\"}"                                                                        
                            ;;
                           
                    *)
                    echo '{"code":"1","output":"invalid method"}'
                    exit 1
        esac #appmanager method
        ;;
esac # ubus method

exit 0
