#!/bin/sh

. /usr/share/libubox/jshn.sh
. /lib/functions.sh

UpdateConfigScript="/bin/UpdateConfigurationsSIAServer ucitoappcfg"
case "$1" in
    list)
        echo '{"configure":{}}'
        ;;
    call)
        case "$2" in
                    configure)
								 response=$($UpdateConfigScript)
                            if [ "$?" -ne 0 ]
                            then
								echo "{\"code\":1,\"output\":\"Failure : Webserver Config Save\"}"
                            else
								echo "{\"code\":0,\"output\":\"Success : Webserver Config Save.Reboot the device for affective change\"}"
                            fi
                                                                                 
                            ;;
                            
                          # response1=$(SystemstartScript)
                           # echo "{\"code\":0,\"output\":\"$file\"}"
                                                      
                           
                    *)
                    echo '{"code":"1","output":"invalid method"}'
                    exit 1
        esac #appmanager method
        ;;
esac # ubus method

exit 0
