#!/bin/sh

[ "${ACTION}" = "remove" -a -n "$PRODUCT" -a -n "$DEVICENAME" -a \( "$DEVICENAME" = "1-1" -o "$DEVICENAME" = "2-1" \) ] || exit 0

. /lib/functions.sh

rm /dev/CWAN1*

/root/InterfaceManager/script/CallUbusInterfaceManager.sh "disable" "CWAN1" &
/root/InterfaceManager/script/CallUbusInterfaceManager.sh "disable" "CWAN1_0" &
/root/InterfaceManager/script/CallUbusInterfaceManager.sh "disable" "CWAN1_1" &
