#!/bin/sh

. /lib/functions.sh

#
# PKG_RELEASE: 1.01
#

#
# Read Modem Configuration file
# 
ReadModemConfigFile()
{
        config_load "$ModemConfigFile"
        config_get ModemEnable "$InterfaceName" modemenable
        config_get DataEnable "$InterfaceName" dataenable
        config_get device "$InterfaceName" device
        config_get ConfiguredComPort "$InterfaceName" comport
        config_get ConfiguredAltComPort "$InterfaceName" altcomport
        config_get PortType "$InterfaceName" porttype
        config_get APN "$InterfaceName" apn
        config_get pdp "$InterfaceName" pdp
        config_get auth "$InterfaceName" auth
        config_get Metric "$InterfaceName" metric
        config_get Proto "$InterfaceName" proto
        # commented as on 6th march 2023 config_get Service "$InterfaceName" service
        config_get Service "$InterfaceName" bandselectenable
        config_get username "$InterfaceName" username
        config_get password "$InterfaceName" password
        config_get protocol "$InterfaceName" protocol
        #ifname auto detect added for mt7621
        config_get ifname "$InterfaceName" ifname     
}

ReadSystemConfigFile()
{
   	config_load "$SystemConfigFile"
   	config_get EnableCellular sysconfig enablecellular
   	config_get CellularOperationModelocal sysconfig CellularOperationMode
   	config_get PrimarySimSwitchBackEnable sysconfig primarysimswitchbackenable
   	config_get PrimarySimSwitchBackTime sysconfig primarysimswitchbacktime
   	config_get productid1 sysconfig productid1
   	config_get productid2 sysconfig productid2
}

ReadSystemGpioFile()
{
   	config_load "$SystemGpioConfig"
	config_get SimSelectGpio gpio simselectgpio
	config_get Sim1SelectValue gpio sim1selectvalue
	config_get Sim2SelectValue gpio sim2selectvalue
	config_get Sim1LedGpio gpio Sim1LedGpio
	config_get Sim1LedGpioOnvalue gpio Sim1LedGpioOnvalue
	config_get Sim1LedGpioOffvalue gpio Sim1LedGpioOffvalue
	config_get Sim2LedGpio gpio Sim2LedGpio
	config_get Sim2LedGpioOnvalue gpio Sim2LedGpioOnvalue
	config_get Sim2LedGpioOffvalue gpio Sim2LedGpioOffvalue
}

#Calling this function everytime after ModemReboot Function is called.
CheckAddIfaceRunningstatus2()
{
	#Exit if the AddIfaceRunningstatus2 flag is set to 1. 
	source /tmp/AddIfaceRunningstatus2
	if [ "$AddIfaceRunningstatus2" = "1" ] 
	then 
		exit 0
	fi
}
#
# Search for Communication & data port and write the same into file 
#
PortSearch()
{
	InterfaceName="$1"
	ConfiguredComPort="$2"
	IPV6InterfaceName="$3"
	
	# Search for symbolically linked ports(generated by udev rule) and copy the same
	ComPortSymLink=$(find /dev -maxdepth 1 -name  "$InterfaceName""_"* | sort | sed -n $ConfiguredComPort"p")
	AltComPortSymLink=$(find /dev -maxdepth 1 -name  "$InterfaceName""_"* | sort | sed -n $ConfiguredAltComPort"p")
	
	sleep 1
	
	#Add ComPortSymLink to modem & sysconfig file. Can be used in any gcom script or in systemstart script.
	if [ "$1" = "CWAN2" ]
	then
		a="2"
	else
		a="1"
	fi
	uci set modem.$1.ComPortSymLink=$ComPortSymLink
	uci set sysconfig.sysconfig.ComPortSymLink$a=$ComPortSymLink
	uci set modem.$1.AltComPortSymLink=$AltComPortSymLink
	uci set sysconfig.sysconfig.AltComPortSymLink$a=$AltComPortSymLink
	uci commit modem
	uci commit sysconfig
	
	sleep 2
	
	echo "<AddInterface_mod2.sh> <PortSearch> The ComPortSymLink for $1=$ComPortSymLink" >> $Logfile2
	
	echo "ComPortSymLink=$ComPortSymLink" > "$PortDetailsFile"
	echo "ComPort=$ComPortSymLink" >> "$PortDetailsFile"
	
	if [ "x$ComPortSymLink" = "x" ]
	then
		echo "status=ComPortLink NE" >> "$PortDetailsFile"
		echo "status=Disabled" > "$AddIfaceStatusFile"
	else
		if [ "$EnableCellular" = "1" ]
		then
			echo "<AddInterface_mod2.sh> <PortSearch> EnableCellular set to 1. " >> $Logfile2
			#Check if the file doesn't exist. This is required during boot because
			#At command sim switch doesn't reset back to sim 1 when modem is rebooted.
			#If this file is there, then, don't run the AT command for sim switch.
			if [ ! -e /tmp/checksimswitch.txt ]
			then
				#Set rm500 and em06 to sim1.
				model=$(uci get modem.$InterfaceName.model)
				
				echo "<AddInterface_mod2.sh> <PortSearch> The modem is = $model" >> $Logfile2
				
				for i in 1 2 3
				do
					#RM500Q & RM500U uses 1 for sim1 and 2 for sim2
					if [ $model = "RM500U" ] || [ $model = "RM500Q" ]
					then
						
						#Just fire one AT command.
						/bin/at-cmd $ComPortSymLink AT
						
						sleep 1
												
						for j in 1 2 3 4
						do	
							Status=$(/bin/at-cmd $ComPortSymLink AT+QUIMSLOT?)
							
							# Extract QUIMSLOT value using awk
							quimslot=$(echo "$Status" | awk '/\+QUIMSLOT:/ {print $2}')

							# Extract OK response
							ok_response=$(echo "$Status" | grep -o 'OK[[:space:]]*$')
							
							# If the value obtained is 1; break.
							if [ "$quimslot" = "1" ]
							then
								echo "<AddInterface_mod2.sh> <PortSearch> On bootup sim switch set to 1. " >> $Logfile2
								done=1
								break
							
							#If the value obtained is 2; then set to sim 1 & reboot the modem.
							elif [ "$quimslot" = "2" ]
							then
								echo "<AddInterface_mod2.sh> <PortSearch> On bootup sim switch is set to 2. " >> $Logfile2
								
								for k in 1 2 3
								do
									echo "<AddInterface_mod2.sh> <PortSearch> Setting the sim to 1. " >> $Logfile2
									
									/bin/at-cmd $ComPortSymLink AT+QUIMSLOT=1
									
									sleep 2
									
									#Create /tmp/checksimswitch.txt, so it sets to sim1 only on boot up & not everytime. 
									touch /tmp/checksimswitch.txt
									
									#Now, reboot the modem.
									if [ "$InterfaceName" = "CWAN1" ] || [ "$InterfaceName" = "CWAN1_0" ] || [ "$InterfaceName" = "CWAN1_1" ]
									then
										echo "<AddInterface_mod2.sh> <PortSearch> Rebooting $InterfaceName after setting simswitch to FIRST sim..." >> $Logfile2
										/root/usrRPC/script/Recycle_WAN1_PWR_Script.sh $ComPortSymLink & 
										exit 0
									elif [ "$InterfaceName" = "CWAN2" ]
									then
										#Setting AddIfaceRunningstatus2 to 1. That is, Donot allow AddInterface to run.
										echo "AddIfaceRunningstatus2=1" > /tmp/AddIfaceRunningstatus2
										
										echo "<AddInterface_mod2.sh> <PortSearch> Rebooting $InterfaceName after setting simswitch to FIRST sim..." >> $Logfile2
										
										/root/usrRPC/script/Recycle_WAN2_PWR_Script.sh $ComPortSymLink &
										exit 0
									fi
								done
							
							#If the value obtained is neither 1 or 2; that is, some junk response, then, check once again.	
							else
								sleep 2
							fi
						done
						
						if [ "$done" = "1" ]
						then
							echo "<AddInterface_mod2.sh> <PortSearch> Sim switch is ALREADY set to 1. " >> $Logfile2
							break
						fi
						
					#EM06 uses 0 for sim1 and 1 for sim2
					elif [ $model = "EM06" ]
					then
						/bin/at-cmd $ComPortSymLink AT+QDSIM=0
					fi
				done
				
				#Create /tmp/checksimswitch.txt, so it sets to sim1 only on boot up & not everytime. 
				touch /tmp/checksimswitch.txt
				
				#Create /tmp/onboot_modemsimswitch.txt, so that the below simcheck after qccid doesn't happen; 
				#since, simnum is always set to 1 on bootup. 
				touch /tmp/modemsimswitch.txt
				
			fi
			
			echo "<AddInterface_mod2.sh> <PortSearch> Checking for qccid ..." >> $Logfile2
			
			#Now get the qccid.
			for i in 1 2 3 4
			do
				simid=$(/usr/bin/gcom -d "$ComPortSymLink" -s "$QccidScript" | awk FNR==2 | cut -d ":" -f 2 | tr -d '\011\012\013\014\015\040')
				
				echo "<AddInterface_mod2.sh> <PortSearch> simid is - $simid" >> $Logfile2
				
				#####################################################################
				#1.07-RC7
				#Added the below for ReadSIMInfo to show the qccid in the others page.
				touch tmp/sim2info.txt 
				echo "Modem 2 QCCID = $simid" > /tmp/sim2info.txt
				#####################################################################
				
				#Check if the simid is just numbers. This is to reject anyother AT cmd response apart from qccid.
				#if  echo "$simid" | grep -q '^[0-9]*$'
				#then
					#Now check, if it's greater than 20 numbers.
					if [ "${#simid}" -gt 10 ]
					then
						status="READY"
					break
					else
						status="NOTREADY"
					fi
				#fi
			done
			
			echo " " >> $Logfile
			echo " " >> $Logfile
			echo "==================================================================" >> $Logfile
			echo "============ $date: $InterfaceName -- $ComPortSymLink ============" >> $Logfile
			echo " " >> $Logfile
			
			#Check if the file modemsimswitch doesn't exist. If there is no modemsimswitch.txt, then this is the 1st bootup.
			#It means, the above simnum check on bootup has been run already. Hence, no need to run the below simcheck twice.
			#since, simnum is always set to 1 on bootup. If the file isn't there, then, break.
			
			if [ ! -e /tmp/modemsimswitch.txt ]
			then
				echo "<AddInterface_mod2.sh> <PortSearch> modemsimswitch.txt is not present. Create it and then break! " >> $Logfile2
				#Creating the file for 1st bootup
				touch /tmp/modemsimswitch.txt 
				#If the file isn't there, then, break. On bootup simnum check has been executed already.
				break
			else
				echo "<AddInterface_mod2.sh> <PortSearch> modemsimswitch.txt is present." >> $Logfile2
				#Check if modemsimnum is same as simnum.
				simnum=$(cat /tmp/simnumfile)
				
				model=$(uci get modem.$InterfaceName.model)
				
				#RM500Q & RM500U uses 1 for sim1 and 2 for sim2
				if [ $model = "RM500U" ] || [ $model = "RM500Q" ]
				then
					echo "<AddInterface_mod2.sh> <PortSearch> For $model, checking if modemsimnum is same as simnum." >> $Logfile2
					
					#Just fire one AT command.
					/bin/at-cmd $ComPortSymLink AT
					
					sleep 1
					
					#Get the QUIMSLOT value 						
					for i in 1 2 3 4
					do	
						Status=$(/bin/at-cmd $ComPortSymLink AT+QUIMSLOT?)
						
						# Extract QUIMSLOT value using awk
						quimslot=$(echo "$Status" | awk '/\+QUIMSLOT:/ {print $2}')
						
						if [ "$quimslot" = "1" ] || [ "$quimslot" = "2" ]
						then
							#Set got_resp as 1, if received response. So as not to switch to alt comport port.
							got_resp=1
							break
						else
							sleep 2
						fi
					done
					
					if [ "$got_resp" = "1" ]
					then
						break
					
					#If no response on comport, then switch to alt comport.
					else
						echo "$date: No response on AT+QUIMSLOT?; switching to alternate comport" >> $Logfile1
						
						for i in 1 2 3 4
						do	
							Status=$(/bin/at-cmd $AltComPortSymLink AT+QUIMSLOT?)
							
							# Extract QUIMSLOT value using awk
							quimslot=$(echo "$Status" | awk '/\+QUIMSLOT:/ {print $2}')
							
							if [ "$quimslot" = "1" ] || [ "$quimslot" = "2" ]
							then
								break
							else
								sleep 2
							fi
						done
						
					fi	
						
					#For dualcellularsinglesim, just make sure that the modem isn't set to sim2.
					if [ "$CellularOperationModelocal" = "dualcellularsinglesim" ]
					then
						if [ $model = "RM500U" ] || [ $model = "RM500Q" ]
						then
							simnum="1"
						fi
					fi
						
					# If the MODEMSIMNUM is same as SIMNUM; break.
					if [ "$quimslot" = "$simnum" ]
					then
						echo "<AddInterface_mod2.sh> <PortSearch> MODEMSIMNUM=$quimslot; SIMNUM=$simnum. " >> $Logfile2
						echo "<AddInterface_mod2.sh> <PortSearch> MODEMSIMNUM is same as SIMNUM. " >> $Logfile2

						break
					
					# If the MODEMSIMNUM is DIFFERENT than SIMNUM; Take simnum as priority & do simswitch.
					else
						echo "<AddInterface_mod2.sh> <PortSearch> MODEMSIMNUM=$quimslot; SIMNUM=$simnum. " >> $Logfile2
						echo "<AddInterface_mod2.sh> <PortSearch> MODEMSIMNUM is DIFFERENT than SIMNUM. " >> $Logfile2
						echo "<AddInterface_mod2.sh> <PortSearch> Setting the sim to $simnum. " >> $Logfile2
						
						for j in 1 2 3
						do	
							/bin/at-cmd $ComPortSymLink AT+QUIMSLOT=$simnum
							
							sleep 2
						done
						
						#Now, reboot the modem.
						if [ "$InterfaceName" = "CWAN1_0" ] || [ "$InterfaceName" = "CWAN1_1" ]
						then
							echo "<AddInterface_mod2.sh> <PortSearch> Rebooting $InterfaceName after setting modemsimnum to $simnum..." >> $Logfile2
							/root/usrRPC/script/Recycle_WAN1_PWR_Script.sh $ComPortSymLink & 
							exit 0
						fi
					fi
				fi
			fi
			
			#If status = READY
			if [ "$status" = "READY" ]
			then
				
				echo "$date: The QCCID is - $simid" >> $Logfile
				echo "$date: The status is - $status" >> $Logfile
				echo " " >> $Logfile
				
				echo "$date: The QCCID is - $simid" >> $Logfile2
				echo "$date: The status is - $status" >> $Logfile2
				
				#Values are set in /etc/config/modemstatus for snmp agent
				uci set modemstatus.modemstatus=interface
				uci set modemstatus.modemstatus.PinState2=$status
				uci set modemstatus.modemstatus.QCCID2=$simid
				uci commit modemstatus
				
				
				# /tmp/simnotready file is created when the status is not ready and deleted if the status is ready.
				# If this file is present, /bin/checkinterfaces.sh doesn't run during systemboot.sh
				rm /tmp/simnotready
				
				#Add network config if sim is ready.
				AddNetworkInterface $InterfaceName $status $IPV6InterfaceName
			
			#If status = NOTREADY
			else
				
				echo "$date: The QCCID is - $simid & the status is - $status" >> $Logfile
				echo "$date: The QCCID is - $simid" >> $Logfile2
				echo "$date: The status is - $status" >> $Logfile2
				
				#Values are set in /etc/config/modemstatus for snmp agent
				uci set modemstatus.modemstatus=interface
				uci set modemstatus.modemstatus.PinState2=$status
				uci set modemstatus.modemstatus.QCCID2=$simid
				uci commit modemstatus
				
				# /tmp/simnotready file is created when the status is not ready and deleted if the status is ready.
				# If this file is present, /bin/checkinterfaces.sh doesn't run during systemboot.sh
				
				touch /tmp/simnotready
				
				if [ "$InterfaceName" = "CWAN1" ]
				then
					#sleep for 2 minutes and reboot the modem. This will go on until it detects qccid.
					
					echo "Rechecking if the $InterfaceName is up in 120 seconds ..." >> $Logfile2
					
					sleep 120
					
					echo "checking Qccid Info ..." >> $Logfile2
					
					QccidInfo
					
					if [ "$status_info" = "NOTREADY" ]
					then
						
						echo "The Qccid status is still not ready. Hence, rebooting." >> $Logfile2
						
						/root/usrRPC/script/Recycle_WAN1_PWR_Script.sh $ComPortSymLink
					fi
					
				elif [ "$InterfaceName" = "CWAN2" ]
				then
					#sleep for 2 minutes and reboot the modem. This will go on until it detects qccid.
					
					echo "Rechecking if the $InterfaceName is up in 120 seconds ..." >> $Logfile2
					
					sleep 120
					
					#Exit if the AddIfaceRunningstatus2 flag is set to 1. 
					CheckAddIfaceRunningstatus2

					echo "checking Qccid Info ..." >> $Logfile2
					
					QccidInfo
					
					#Exit if the AddIfaceRunningstatus2 flag is set to 1. 
					CheckAddIfaceRunningstatus2

					if [ "$status_info" = "NOTREADY" ]
					then
					
						echo "The Qccid status is still not ready. Hence, rebooting." >> $Logfile2
						
						#Setting AddIfaceRunningstatus2 to 1. That is, Donot allow AddInterface to run.
						echo "AddIfaceRunningstatus2=1" > /tmp/AddIfaceRunningstatus2
						
						/root/usrRPC/script/Recycle_WAN2_PWR_Script.sh $ComPortSymLink

						#Exit if the AddIfaceRunningstatus2 flag is set to 1. 
						CheckAddIfaceRunningstatus2
					fi
				fi
				
				if [ "$InterfaceName" = "CWAN1_0" ]
				then
					echo "The Qccid status is not ready. Hence, switching to sim 2." >> $Logfile2
					
					/root/InterfaceManager/script/SimSwitch.sh CWAN1 2
					if [ "$PrimarySimSwitchBackEnable" = "1" ]
					then
						pid=$(pgrep -f "/root/InterfaceManager/script/PrimarySwitch.sh")
						kill -TERM "$pid" > /dev/null 2>&1
						sleep 1
						kill -KILL "$pid" > /dev/null 2>&1
						/root/InterfaceManager/script/PrimarySwitch.sh "$PrimarySimSwitchBackTime" CWAN1 1 &         
					fi
				fi
				if [ "$InterfaceName" = "CWAN1_1" ]
				then
					echo "The Qccid status is not ready. Hence, switching to sim 1." >> $Logfile2
					/root/InterfaceManager/script/SimSwitch.sh CWAN1 1
				fi
			fi
		fi
		
	#For qnetdevctl.sh.
	echo "0" > /tmp/qnetdevctl2
		
	fi 
	      
}

#
# Update network configuration file
# 

# Function to check if a GPIO exists
check_gpio_existence() {
    local gpio="$1"
    if [ -d "/sys/class/gpio/gpio$gpio" ]; then
		echo "<AddInterface.sh><check_gpio_existence>GPIO $gpio exists" >> $Logfile2
        return 0  # GPIO exists
    else
		echo "<AddInterface.sh><check_gpio_existence>GPIO $gpio doesn't exists" >> $Logfile2
        return 1  # GPIO does not exist
    fi
}

#SIM LEDS
SimLeds(){
	
	InterfaceName="$1"
	status="$2"

	# Check and export Sim1LedGpio if it doesn't exist
	if ! check_gpio_existence "$Sim1LedGpio"; then
		echo "$Sim1LedGpio" > /sys/class/gpio/export
		echo out > "/sys/class/gpio/gpio$Sim1LedGpio/direction"
		echo "<AddInterface.sh><SimLeds>Exported and configured $Sim1LedGpio" >> $Logfile2
	fi

	# Check and export Sim2LedGpio if it doesn't exist
	if ! check_gpio_existence "$Sim2LedGpio"; then
		echo "$Sim2LedGpio" > /sys/class/gpio/export
		echo out > "/sys/class/gpio/gpio$Sim2LedGpio/direction"
		echo "<AddInterface.sh><SimLeds>Exported and configured $Sim2LedGpio" >> $Logfile2
	fi

}

#Run operatorlock script  
UpdateOperatorLock()
{                           
    $Updateoperatorlock "AddInterface_mod2"  
}

AddNetworkInterface()
{
	InterfaceName="$1"
	status="$2"
	IPV6InterfaceName="$3"
	
	#Exit if the AddIfaceRunningstatus2 flag is set to 1. 
	CheckAddIfaceRunningstatus2
	
	#Run bandlock script
	$Updatebandlock "AddInterface_mod2"
	
	sleep 1
	
	#Check if xlat is enabled 
	Enablexlatsim1=$(uci get sysconfig.sysconfig.Enable464xlatSim1)
	Enablexlatsim2=$(uci get sysconfig.sysconfig.Enable464xlatSim2)
	
	echo "<AddInterface_mod2.sh><AddNetworkInterface> Enablexlatsim1=$Enablexlatsim1" >> $Logfile2
	echo "<AddInterface_mod2.sh><AddNetworkInterface> Enablexlatsim2=$Enablexlatsim2" >> $Logfile2
	
	if [ "$CellularOperationModelocal" = "dualcellularsinglesim" ]
	then
		if ([ "$Enablexlatsim1" = "1" ] && [ "$IPV6InterfaceName" = "wan6c1" ])
		then
			uci set network.${IPV6InterfaceName}_xlat=interface
			uci set network.${IPV6InterfaceName}_xlat.proto='464xlat'
			uci set network.${IPV6InterfaceName}_xlat.tunlink=$IPV6InterfaceName
			uci set network.${IPV6InterfaceName}_xlat.ip6prefix='64:ff9b::/96'
		elif ([ "$Enablexlatsim2" = "1" ] && [ "$IPV6InterfaceName" = "wan6c2" ]) 
		then
			uci set network.${IPV6InterfaceName}_xlat=interface
			uci set network.${IPV6InterfaceName}_xlat.proto='464xlat'
			uci set network.${IPV6InterfaceName}_xlat.tunlink=$IPV6InterfaceName
			uci set network.${IPV6InterfaceName}_xlat.ip6prefix='64:ff9b::/96'
		fi
	else
		if ([ "$Enablexlatsim1" = "1" ] && [ "$IPV6InterfaceName" = "wan6c1" ]) || ([ "$Enablexlatsim2" = "1" ] && [ "$IPV6InterfaceName" = "wan6c2" ]) 
		then
			uci set network.${IPV6InterfaceName}_xlat=interface
			uci set network.${IPV6InterfaceName}_xlat.proto='464xlat'
			uci set network.${IPV6InterfaceName}_xlat.tunlink=$IPV6InterfaceName
			uci set network.${IPV6InterfaceName}_xlat.ip6prefix='64:ff9b::/96'
		fi
	fi
	
	#cdcether
	if [ "$protocol" = "cdcether" ]
	then
		#IPV4
		if [ "$pdp" = "1" ] 				
		then
			uci set network."$InterfaceName"=interface
			uci set network."$InterfaceName".ifname="$ifname"
			uci set network."$InterfaceName".proto="dhcp"
			uci set network."$InterfaceName".metric="$Metric"
		#IPV6
		elif [ "$pdp" = "2" ]
		then 
			uci set network."$IPV6InterfaceName"=interface
			uci set network."$IPV6InterfaceName".ifname="$ifname"
			uci set network."$IPV6InterfaceName".proto="dhcpv6"
			#Need sourcefilter for dual modem ipv6
			uci set network."$IPV6InterfaceName".sourcefilter="0"
			uci set network."$IPV6InterfaceName".metric="$Metric" 
			uci set network."$IPV6InterfaceName".reqaddress="try" 
			uci set network."$IPV6InterfaceName".reqprefix="auto"
		#IPV4V6
		elif [ "$pdp" = "3" ] 
		then  
			uci set network."$InterfaceName"=interface
			uci set network."$InterfaceName".ifname="$ifname"
			uci set network."$InterfaceName".proto="dhcp"
			uci set network."$InterfaceName".metric="$Metric" 
			
			uci set network."$IPV6InterfaceName"=interface
			uci set network."$IPV6InterfaceName".ifname="$ifname"
			#Need sourcefilter for dual modem ipv6
			uci set network."$IPV6InterfaceName".sourcefilter="0"
			uci set network."$IPV6InterfaceName".proto="dhcpv6"
			uci set network."$IPV6InterfaceName".metric="$Metric" 
			uci set network."$IPV6InterfaceName".reqaddress="try" 
			uci set network."$IPV6InterfaceName".reqprefix="auto"
		fi
		
		uci commit network

		#Execute AT commands
		SetATCommands $InterfaceName $ComPortSymLink
		
		echo "<AddInterface_mod2.sh><AddNetworkInterface> SetATCommands done!" >> $Logfile2
		
	#QMI
	else
		if [ "$auth" = "1" ]
		then 
			 authentication=PAP
		elif [ "$auth" = "2" ]
		then
			 authentication=CHAP
		fi
		
		#IPV4
		if [ "$pdp" = "1" ] 				
		then		
			uci set network."$InterfaceName"=interface
			uci set network."$InterfaceName".ifname="$ifname"
			uci set network."$InterfaceName".proto="qmi"
			uci set network."$InterfaceName".device="/dev/$device"                                                                
			uci set network."$InterfaceName".apn="$APN"
			uci set network."$InterfaceName".pdptype="ipv4"                                                                
			uci set network."$InterfaceName".metric="$Metric"
			if [ "$auth" = "1" ] ||  [ "$auth" = "2" ]
			then
				uci set network."$InterfaceName".auth="$authentication"
				uci set network."$InterfaceName".username="$username"
				uci set network."$InterfaceName".password="$password"
			fi	
		#IPV6
		elif [ "$pdp" = "2" ]
		then 
			uci set network."$IPV6InterfaceName"=interface
			uci set network."$IPV6InterfaceName".ifname="$ifname"
			uci set network."$IPV6InterfaceName".proto="qmi"
			uci set network."$IPV6InterfaceName".apn="$APN"
			uci set network."$IPV6InterfaceName".metric="$Metric" 
			uci set network."$IPV6InterfaceName".device="/dev/$device"                                                                
			uci set network."$IPV6InterfaceName".pdptype="ipv6"                                                                
			uci set network."$IPV6InterfaceName".ipv6="1" 
	
			if [ "$auth" = "1" ] ||  [ "$auth" = "2" ]
			then
				uci set network."$IPV6InterfaceName".auth="$authentication"
				uci set network."$IPV6InterfaceName".username="$username"
				uci set network."$IPV6InterfaceName".password="$password"
			fi
		#IPV4V6
		elif [ "$pdp" = "3" ] 
		then  
			uci set network."$InterfaceName"=interface
			uci set network."$InterfaceName".ifname="$ifname"
			uci set network."$InterfaceName".proto="qmi"
			uci set network."$InterfaceName".device="/dev/$device"                                                                
			uci set network."$InterfaceName".apn="$APN"
			uci set network."$InterfaceName".pdptype="ipv4v6"                                                                
			uci set network."$InterfaceName".metric="$Metric"
			if [ "$auth" = "1" ] ||  [ "$auth" = "2" ]
			then
				uci set network."$InterfaceName".auth="$authentication"
				uci set network."$InterfaceName".username="$username"
				uci set network."$InterfaceName".password="$password"
			fi
		fi	
		
		uci commit network

		#Execute AT commands
		SetATCommandsQMI $InterfaceName $ComPortSymLink
		
		echo "<AddInterface_mod2.sh><AddNetworkInterface> SetATCommandsQMI done!" >> $Logfile2
		
	fi 
	
	#Run operatorlock Function
	UpdateOperatorLock
	
	#Exit if the AddIfaceRunningstatus2 flag is set to 1. 
	CheckAddIfaceRunningstatus2
	
	ifup "$InterfaceName" > /dev/null 2>&1
	sleep 1
	ifup "$IPV6InterfaceName" > /dev/null 2>&1
	sleep 1
	mwan3 ifup "$InterfaceName" > /dev/null 2>&1
	sleep 1
	mwan3 ifup "$IPV6InterfaceName" > /dev/null 2>&1
	
	echo "<AddInterface_mod2.sh><AddNetworkInterface> $InterfaceName protocol=$protocol pdp=$pdp" >> $Logfile2
	echo "<AddInterface_mod2.sh><AddNetworkInterface> $InterfaceName ifup done!" >> $Logfile2
	echo "<AddInterface_mod2.sh><AddNetworkInterface> $IPV6InterfaceName ifup done!" >> $Logfile2
	echo "status=Enabled" > "$AddIfaceStatusFile"
	
	echo "<AddInterface_mod2.sh><AddNetworkInterface> <SimLeds>" >> $Logfile2
	
	#Glow the sim leds.	
	SimLeds $InterfaceName $status
	
	#to glow signal strength led's
	/root/InterfaceManager/script/Update_Analytics_data.sh > /dev/null 2>&1
	
}

QccidInfo(){

	for i in 1 2 3
	do
		simid=$(/usr/bin/gcom -d "$ComPortSymLink" -s "$QccidScript" | awk FNR==2 | cut -d ":" -f 2)
		if [ "${#simid}" -gt 10 ]
		then
			status_info="READY"
			#Add network config if sim is ready.
			AddNetworkInterface $InterfaceName $status_info $IPV6InterfaceName
		else
			status_info="NOTREADY"
		fi
	done

}

ModemReboot() {
	InterfaceName=$1
	ComPortSymLink=$2
	
	echo "$date: Rebooting $InterfaceName ..." >> $Logfile2
	#Setting AddIfaceRunningstatus2 to 1. That is, Donot allow AddInterface to run.
	echo "AddIfaceRunningstatus2=1" > /tmp/AddIfaceRunningstatus1
	
	if [ "$InterfaceName" = "CWAN1" ]
	then
		echo "$date: Rebooting CWAN1 ..." >> $Logfile
		echo "<AddInterface_mod2.sh> <ModemReboot> Rebooting CWAN1 ..." >> $Logfile2
		echo 1 > "$SimNumFile"
		/root/usrRPC/script/Recycle_WAN1_PWR_Script.sh $ComPortSymLink & 
		break
	elif [ "$InterfaceName" = "CWAN2" ]
	then
		echo "$date: Rebooting CWAN2 ..." >> $Logfile
		echo "<AddInterface_mod2.sh> <ModemReboot> Rebooting CWAN2 ..." >> $Logfile2
		/root/usrRPC/script/Recycle_WAN2_PWR_Script.sh $ComPortSymLink & 
		break
	elif [ "$InterfaceName" = "CWAN1_0" ]
	then
		echo "$date: Rebooting CWAN1_0 ..." >> $Logfile
		echo "<AddInterface_mod2.sh> <ModemReboot> Rebooting CWAN1_0 ..." >> $Logfile2
		echo 1 > "$SimNumFile"
		/root/usrRPC/script/Recycle_WAN1_PWR_Script.sh $ComPortSymLink & 
		break
		
	elif [ "$InterfaceName" = "CWAN1_1" ]
	then
		echo "$date: Rebooting CWAN1_1 ..." >> $Logfile
		echo "<AddInterface_mod2.sh> <ModemReboot> Rebooting CWAN1_1 ..." >> $Logfile2
		
		#If the modem works on sim2, then sim2 should be up, not sim1.
		/root/InterfaceManager/script/SimSwitch.sh CWAN1 2
		if [ "$PrimarySimSwitchBackEnable" = "1" ]
		then
			pid=$(pgrep -f "/root/InterfaceManager/script/PrimarySwitch.sh")
			kill -TERM "$pid" > /dev/null 2>&1
			sleep 1
			kill -KILL "$pid" > /dev/null 2>&1
			/root/InterfaceManager/script/PrimarySwitch.sh "$PrimarySimSwitchBackTime" CWAN1 1 &         
		fi
		break
	fi
	exit 0
}

SetATCommands() {
	
	#Exit if the AddIfaceRunningstatus2 flag is set to 1. 
	CheckAddIfaceRunningstatus2
	
	date=$(date) 
	
	InterfaceName=$1
	ComPortSymLink=$2
	
	model=$(uci get modem.$InterfaceName.model)
	AltComPortSymLink=$(uci get modem.$InterfaceName.AltComPortSymLink)
	
	echo "------ $date: SetATCommands $InterfaceName -- $ComPortSymLink ------" >> $Logfile
	echo "<AddInterface_mod2.sh><SetATCommands> $InterfaceName -- $ComPortSymLink" >> $Logfile2
	
	#To check sim status. It should come ready. It should come within 20 sec
	for i in 1 2 3                                                                                                                  
	do 
		Status=$(/bin/at-cmd "$ComPortSymLink" AT+CPIN? | awk NR==2 | cut -d ":" -f 2 | tr -d '\011\012\013\014\015\040')
		if [ $Status = "READY" ]
		then
			echo "$date:AT+CPIN=$Status,CPIN is Ready" >> $Logfile
			echo "$date:AT+CPIN=$Status,CPIN is Ready" >> $Logfile2
			break
		else
			sleep 3
		fi
	done
	
	if [ "$Status" != "READY" ]
	then
		echo "$date:[AT+CPIN=$Status]CPIN is not Ready. Hence, checking on AltComPort." >> $Logfile
		echo "$date:[AT+CPIN=$Status]CPIN is not Ready. Hence, checking on AltComPort." >> $Logfile2
		
		for i in 1 2 3                                                                                                                  
		do
		
			Status_Alt=$(/bin/at-cmd "$AltComPortSymLink" AT+CPIN? | awk NR==2 | cut -d ":" -f 2 | tr -d '\011\012\013\014\015\040')
			if [ "$Status_Alt" = "READY" ]
			then
				echo "$date:AT+CPIN=$Status,CPIN is Ready" >> $Logfile
				echo "$date:AT+CPIN=$Status,CPIN is Ready" >> $Logfile2
				break
			else
				sleep 3
			fi
		done
		
		if [ "$Status_Alt" != "READY" ]
		then
			echo "$date:[AT+CPIN=$Status]CPIN is not Ready. Hence, rebooting." >> $Logfile
			echo "$date:[AT+CPIN=$Status]CPIN is not Ready. Hence, rebooting." >> $Logfile2
			
			#Reboot/switch sim depending on the interface name.
			ModemReboot $InterfaceName $ComPortSymLink
			
			#Exit if the AddIfaceRunningstatus2 flag is set to 1. 
			CheckAddIfaceRunningstatus2
		fi
	fi
	
	#Doesn't work for RM500U. So, skip it.
	if [ $model != "RM500U" ]
	then
	
		#To check if it is registered in circuit switched network. should happen within 90 sec.
		#output should be 0,1.
		for i in 1 2 3                                                                                                                  
		do 
			Status=$(/bin/at-cmd "$ComPortSymLink" AT+CREG? | awk NR==2 | cut -d ":" -f 2 | cut -d "," -f 2 | tr -d '\011\012\013\014\015\040')

			if [ $Status = "1" ]
			then
				echo "$date:[AT+CREG?=$Status]Sim is Successfully Registered" >> $Logfile
				echo "$date:[AT+CREG?=$Status]Sim is Successfully Registered" >> $Logfile2
				break
			else
				sleep 3
			fi
		done
		
		if [ "$Status" != "1" ]
		then
			echo "$date:[AT+CREG?=$Status]Sim is not Successfully Registered" >> $Logfile
			echo "$date:[AT+CREG?=$Status]Sim is not Successfully Registered" >> $Logfile2
		fi
		
		#To check Registration status.
		#output should be 0,1.
		for i in 1 2 3                                                                                                                  
		do 
			Status=$(/bin/at-cmd "$ComPortSymLink" AT+CGREG? | awk NR==2 | cut -d ":" -f 2 | cut -d "," -f 2 | tr -d '\011\012\013\014\015\040')

			if [ $Status = "1" ]
			then
				echo "$date: The sim is registered for AT+CGREG & the status is ="$Status >> $Logfile
				echo "$date: The sim is registered for AT+CGREG & the status is =$Status" >> $Logfile2
				break
			else
				sleep 3
			fi
		done
		
		if [ "$Status" != "1" ]
		then
			echo "$date: The sim is NOT registered for AT+CGREG & the status is ="$Status >> $Logfile
			echo "$date: The sim is 'NOT' registered for AT+CGREG & the status is =$Status" >> $Logfile2
			#Reboot/switch sim depending on the interface name.
			#ModemReboot $InterfaceName $ComPortSymLink
		fi
	fi
	
	#Check AT+COPS?
	for i in 1 2                                                                                                                 
	do
		echo "$date: Checking for AT+COPS?" >> $Logfile
		echo "$date: Checking for AT+COPS?" >> $Logfile2
		Status=$(/bin/at-cmd $ComPortSymLink AT+COPS? | sed -n '2p' | tr -d '\011\012\013\014\015\040') 
		
		if [ "$Status" = "+COPS: 0" ]                                                                                                        
		then
			echo "$date: The status of AT+COPS? is $Status. Hence, rebooting ..." >> $Logfile
			echo "$date: The status of AT+COPS? is $Status. Hence, rebooting ..." >> $Logfile2

			#Reboot/switch sim depending on the interface name.
			ModemReboot $InterfaceName $ComPortSymLink
			
			#Exit if the AddIfaceRunningstatus2 flag is set to 1. 
			CheckAddIfaceRunningstatus2
			
			break                                                                                                                     
		elif [ -z "$Status" ]
		then
			echo "$date: The status of AT+COPS? is unavailable. Hence, checking on AltComPort." >> $Logfile
			echo "$date: The status of AT+COPS? is unavailable. Hence, checking on AltComPort." >> $Logfile2
			
			Status_alt=$(/bin/at-cmd $AltComPortSymLink AT+COPS? | sed -n '2p' | tr -d '\011\012\013\014\015\040')
			
			echo "$date: The status of AT+COPS? is $Status_alt." >> $Logfile
			echo "$date: The status of AT+COPS? is $Status_alt." >> $Logfile2
			
			if [ "$Status_alt" = "+COPS: 0" ]                                                                                                        
			then
				echo "$date: The status of AT+COPS? is $Status_alt. Hence, rebooting ..." >> $Logfile
				echo "$date: The status of AT+COPS? is $Status_alt. Hence, rebooting ..." >> $Logfile2

				#Reboot/switch sim depending on the interface name.
				ModemReboot $InterfaceName $AltComPortSymLink
				
				#Exit if the AddIfaceRunningstatus2 flag is set to 1. 
				CheckAddIfaceRunningstatus2
				
				break
			else
				echo "$date: The status of AT+COPS? is $Status_alt." >> $Logfile
				echo "$date: The status of AT+COPS? is $Status_alt." >> $Logfile2
				break
			fi
		else
			echo "$date: The status of AT+COPS? is $Status." >> $Logfile
			echo "$date: The status of AT+COPS? is $Status." >> $Logfile2
			break
		fi
	done 
	
	#Check for the set pdp, APN & authentication. 
	for i in 1 2                                                                                                                 
	do
		Status=$(/bin/at-cmd $ComPortSymLink AT+QICSGP=1 | awk NR==2 | awk '{print $2}' | tr -d '\011\012\013\014\015\040')
		pdp_stat=$(echo $Status | awk -F',' '{print $1}' | tr -d '\011\012\013\014\015\040')                           
		apn_stat=$(echo $Status | awk -F',' '{print $2}' | awk -F'"' '{print $2}' | tr -d '\011\012\013\014\015\040')                           
		auth_stat=$(echo $Status | awk -F',' '{print $5}' | tr -d '\011\012\013\014\015\040') 
		if [ ! -n "$Status" ]                                                                                                        
		then                                                                                                                           
			sleep 1                                                                                                                     
		else                                                                                                                           
			break                                                                                                                    
		fi                                                                                                                             
	done 
	
	echo "$date: The status obtained for AT+QICSGP cmd is = "$Status >> $Logfile
	echo "$date: The Default PDP set in modem is = $pdp_stat" >> $Logfile
	echo "$date: The Required PDP is = $pdp" >> $Logfile
	echo "$date: The Default APN set in modem is = $apn_stat" >> $Logfile
	echo "$date: The Required APN is = $APN" >> $Logfile
	echo "$date: The Default Auth is set in modem= $auth_stat" >> $Logfile
	echo "$date: The Required Auth is = $auth" >> $Logfile
	
	echo "$date: The status obtained for AT+QICSGP cmd is = "$Status >> $Logfile2
	echo "$date: The Default PDP set in modem is = $pdp_stat" >> $Logfile2
	echo "$date: The Required PDP is = $pdp" >> $Logfile2
	echo "$date: The Default APN set in modem is = $apn_stat" >> $Logfile2
	echo "$date: The Required APN is = $APN" >> $Logfile2
	echo "$date: The Default Auth is set in modem= $auth_stat" >> $Logfile2
	echo "$date: The Required Auth is = $auth" >> $Logfile2
	
	#If status is empty.
	if [ ! -n "$Status" ]
	then
		echo "$date: The status is empty for AT+QICSGP cmd. Hence, checking on AltComPort." >> $Logfile
		echo "$date: The status is empty for AT+QICSGP cmd. Hence, checking on AltComPort." >> $Logfile2
		
		for i in 1 2                                                                                                                 
		do
			Status_Alt=$(/bin/at-cmd $AltComPortSymLink AT+QICSGP=1 | awk NR==2 | awk '{print $2}' | tr -d '\011\012\013\014\015\040')
			if [ ! -n "$Status_Alt" ]                                                                                                        
			then                                                                                                                           
				sleep 1                                                                                                                     
			else                                                                                                                           
				break                                                                                                                    
			fi                                                                                                                             
		done 
		
		pdp_stat=$(echo $Status_Alt | awk -F',' '{print $1}' | tr -d '\011\012\013\014\015\040')                           
		apn_stat=$(echo $Status_Alt | awk -F',' '{print $2}' | awk -F'"' '{print $2}' | tr -d '\011\012\013\014\015\040')                           
		auth_stat=$(echo $Status_Alt | awk -F',' '{print $5}' | tr -d '\011\012\013\014\015\040')
	fi	
	
	#If the pdp, APN & authentication are different, only then, set them using QICSGP command.
	if [ "$pdp_stat" != "$pdp" ] || [ "$apn_stat" != "$APN" ] || [ "$auth_stat" != "$auth" ]
	then
		echo "$date: pdp, APN & authentication are DIFFERENT." >> $Logfile
		echo "$date: pdp, APN & authentication are DIFFERENT." >> $Logfile2

		#Set APN
		for i in 1 2                                                                                                                 
		do
			echo "$date: Setting pdp, APN & authentication...." >> $Logfile
			echo "$date: Setting pdp, APN & authentication...." >> $Logfile2
			Status=$(/bin/at-cmd $ComPortSymLink AT+QICSGP=1,"$pdp",\"$APN\",\"$username\",\"$password\","$auth" | awk NR==2 | tr -d '\011\012\013\014\015\040') 
			
			if [ "$Status" = "OK" ]                                                                                                        
			then
				echo "$date: APN ,PDP,Auth is set Successfully." >> $Logfile
				echo "$date: Deactivating the pdp context using AT+QIDEACT=1." >> $Logfile
				echo "$date: APN ,PDP,Auth is set Successfully." >> $Logfile2
				echo "$date: Deactivating the pdp context using AT+QIDEACT=1." >> $Logfile2
				#Deactivate the pdp context.
				/bin/at-cmd $ComPortSymLink AT+QIDEACT=1
				
				sleep 1

				#Reboot/switch sim depending on the interface name.
				ModemReboot $InterfaceName $ComPortSymLink
				
				#Exit if the AddIfaceRunningstatus2 flag is set to 1. 
				CheckAddIfaceRunningstatus2
				
				break                                                                                                                     
			else                                                                                                                           
				sleep 3                                                                                                                    
			fi                                                                                                                           
		done 
		
		if [ "$Status" != "OK" ]
		then
			echo "$date:AT+QICSGP At command Status is $Status, status not OK when apn,pdp is not set Successfully" >> $Logfile
			echo "$date:AT+QICSGP At command Status is $Status, status not OK when apn,pdp is not set Successfully" >> $Logfile2
			
			#Reboot/switch sim depending on the interface name.
			ModemReboot $InterfaceName $ComPortSymLink
			
			#Exit if the AddIfaceRunningstatus2 flag is set to 1. 
			CheckAddIfaceRunningstatus2
	
		fi

	#If the pdp, APN & authentication are same.
	else
		echo "$date: pdp, APN & authentication are SAME." >> $Logfile
		echo "$date: pdp, APN & authentication are SAME." >> $Logfile2
		#Activate pdp context 1. Get response -- either OK/Error.
		for i in 1 2 3                                                                                                                    
		do
			Status=$(/bin/at-cmd $ComPortSymLink AT+QIACT=1 | awk NR==2 | tr -d '\011\012\013\014\015\040')
									 
			if [ "$Status" = "OK" ]                                                                                                        
			then
				echo "$date: AT+QIACT=1 = Activated pdp context 1." >> $Logfile
				echo "$date: AT+QIACT=1 = Activated pdp context 1." >> $Logfile2
				break                                                                                                                     
			else                                                                                                                           
				sleep 3                                                                                                                    
			fi                                                                                                                             
		done 
		
		#If the response of AT+QIACT=1 is error or if it has no response.
		if [ "$Status" != "OK" ]
		then
			echo "$date: The status of AT+QIACT=1 cmd is not OK & it is = "$Status >> $Logfile
			echo "$date: The status of AT+QIACT=1 cmd is not OK & it is = "$Status >> $Logfile2
			
			#echo "AT+QIDEACT=1 Deactivate the pdp context." >> $Logfile
			#Deactivate and then reboot
			#/bin/at-cmd $ComPortSymLink AT+QIDEACT=1
			#sleep 1
			#Reboot/switch sim depending on the interface name.
			#ModemReboot $InterfaceName $ComPortSymLink
			
		#If the response of AT+QIACT=1 is OK
		else
			#check if pdp is activated/not.
			for i in 1 2 3                                                                                                                    
			do	
				#To get only IP we use here (cut -d "," -f 4)
				Status=$(/bin/at-cmd $ComPortSymLink AT+QIACT? | awk NR==2 | cut -d "," -f 4 | tr -d '\011\012\013\014\015\040')
				Status=$(echo $Status | tr -d '"')
				echo "$date: The status of AT+QIACT? cmd is = $Status" >> $Logfile
				echo "$date: The status of AT+QIACT? cmd is = $Status" >> $Logfile2
				
				#For ipv4 -
				if [ "$pdp" = "1" ]
				then
					ipaddr=$(echo $Status | cut -d "," -f 4 | tr -d -c '.' | wc -c | tr -d '\011\012\013\014\015\040')
					echo "$date: It's an IPV4 address" >> $Logfile
					echo "$date: It's an IPV4 address" >> $Logfile2
					
					#ipv4 has 3 dots (.)                         
					if [ "$ipaddr" = "3" ]                                                                                                        
					then
						break
					else
						echo "$date: The IPv4 address obtained is incorrect. It has '$ipaddr' dots." >> $Logfile
						echo "$date: The IPv4 address obtained is incorrect. It has '$ipaddr' dots." >> $Logfile2
						#Reboot/switch sim depending on the interface name.
						#ModemReboot $InterfaceName $ComPortSymLink
					fi
				
				#For ipv6 -
				elif [ "$pdp" = "2" ]
				then
					ipaddr=$(echo $Status | cut -d "," -f 4 | cut -d ":" -f 1 | awk -F'"' '{print $2}' | tr -d '\011\012\013\014\015\040')
					echo "$date: It's an IPV6 address" >> $Logfile
					echo "$date: It's an IPV6 address" >> $Logfile2
					
					#ipv6 starting addr should be greater then 2000                         
					if [ "$ipaddr" -gt "2000" ]                                                                                                        
					then
						break
					else
						echo "$date: The IPv6 address obtained is incorrect. It has '$ipaddr' starting address." >> $Logfile
						echo "$date: The IPv6 address obtained is incorrect. It has '$ipaddr' starting address." >> $Logfile2
						#Reboot/switch sim depending on the interface name.
						#ModemReboot $InterfaceName $ComPortSymLink
					fi
				
				#For ipv4v6 -
				elif [ "$pdp" = "3" ]
				then
					ipaddr1=$(echo $Status | cut -d "," -f 4 | tr -d -c '.' | wc -c | tr -d '\011\012\013\014\015\040')
					ipaddr2=$(echo $Status | cut -d "," -f 5 | cut -d ":" -f 1 | tr -d '\011\012\013\014\015\040')
					echo "$date: It's an IPV4V6 address" >> $Logfile
					echo "$date: It's an IPV4V6 address" >> $Logfile2
					
					#ipv6 starting addr should be greater then 2000 & ipv4 has 3 dots (.)                        
					if [ "$ipaddr1" = "3" ] && [ "$ipaddr2" -gt "2000" ]                                                                                                    
					then
						break
					else
						echo "$date: The IPv6 address obtained is incorrect. It has '$ipaddr1' dots & '$ipaddr2' starting address." >> $Logfile
						echo "$date: The IPv6 address obtained is incorrect. It has '$ipaddr1' dots & '$ipaddr2' starting address." >> $Logfile2
						#Reboot/switch sim depending on the interface name.
						#ModemReboot $InterfaceName $ComPortSymLink
					fi
				
				#For wrong pdp
				else
					echo "$date: Wrong pdp set. Rebooting ..." >> $Logfile
					echo "$date: Wrong pdp set. Rebooting ..." >> $Logfile2
					#Reboot/switch sim depending on the interface name.
					ModemReboot $InterfaceName $ComPortSymLink
					
					#Exit if the AddIfaceRunningstatus2 flag is set to 1. 
					CheckAddIfaceRunningstatus2
				fi                                                                                                                         
			done
		fi
	fi
	
	exec 200>"$ComPortSymLink"
	flock -n 200
	
	#Get AltComPortSymLink for qnetdevctl.
	AltComPortSymLink=$(uci get modem.$InterfaceName.AltComPortSymLink)
	
	Status_ok=$(/bin/at-cmd "$ComPortSymLink" AT+QNETDEVCTL=1,1,1 | awk NR==2 | tr -d '\011\012\013\014\015\040')
	
	#If response is ok; then break.
	if [ "$Status_ok" = "OK" ]
	then
		echo "$date: AT+QNETDEVCTL=$Status_ok" >> $Logfile
		echo "$date: AT+QNETDEVCTL=$Status_ok" >> $Logfile2
		break 
	#If no response, then try again 3 times
	else
		sleep 2
		echo "$date: AT+QNETDEVCTL=$Status_ok" >> $Logfile
		echo "$date: AT+QNETDEVCTL=$Status_ok" >> $Logfile2
		
		for i in 1 2 3                                                                                                                   
		do
			Status=$(/bin/at-cmd "$ComPortSymLink" AT+QNETDEVCTL=1,1,1 | awk NR==2 | tr -d '\011\012\013\014\015\040')
			
			if [ "$Status" = "OK" ]
			then
				echo "$date: AT+QNETDEVCTL=$Status" >> $Logfile
				echo "$date: AT+QNETDEVCTL=$Status" >> $Logfile2
				
				#Set got_ok as 1, if received ok as response. So as not to switch to alt comport port.
				got_ok=1
				break 
			else
				sleep 2
				echo "$date: AT+QNETDEVCTL=$Status" >> $Logfile
				echo "$date: AT+QNETDEVCTL=$Status" >> $Logfile2
			fi
		done
		
		if [ "$got_ok" = "1" ]
		then
			break
		
		#If no response on comport, then switch to alt comport.
		else
			echo "$date: No response on AT+QNETDEVCTL; switching to alternate comport" >> $Logfile
			echo "$date: No response on AT+QNETDEVCTL; switching to alternate comport" >> $Logfile2
			
			for i in 1 2 3                                                                                                                   
			do
				Status_alt=$(/bin/at-cmd "$AltComPortSymLink" AT+QNETDEVCTL=1,1,1 | awk NR==2 | tr -d '\011\012\013\014\015\040')
				
				if [ "$Status_alt" = "OK" ]
				then
					echo "$date: AT+QNETDEVCTL=$Status_alt for AltComPort" >> $Logfile
					echo "$date: AT+QNETDEVCTL=$Status_alt for AltComPort" >> $Logfile2
					break 
				else
					sleep 2
					echo "$date: AT+QNETDEVCTL=$Status_alt for AltComPort" >> $Logfile
					echo "$date: AT+QNETDEVCTL=$Status_alt for AltComPort" >> $Logfile2
				fi
			done
		fi
	fi
	flock -u 200
}

SetATCommandsQMI() {
	
	#Exit if the AddIfaceRunningstatus2 flag is set to 1. 
	CheckAddIfaceRunningstatus2
	
	date=$(date) 
	
	InterfaceName=$1
	ComPortSymLink=$2
	
	model=$(uci get modem.$InterfaceName.model)
	AltComPortSymLink=$(uci get modem.$InterfaceName.AltComPortSymLink)
	
	echo "------ $date: SetATCommandsQMI $InterfaceName -- $ComPortSymLink ------" >> $Logfile
	echo "<AddInterface_mod2.sh><SetATCommandsQMI> $InterfaceName -- $ComPortSymLink" >> $Logfile2
	
	#To check sim status. It should come ready. It should come within 20 sec
	for i in 1 2 3                                                                                                                  
	do 
		Status=$(/bin/at-cmd "$ComPortSymLink" AT+CPIN? | awk NR==2 | cut -d ":" -f 2 | tr -d '\011\012\013\014\015\040')
		if [ $Status = "READY" ]
		then
			echo "$date:AT+CPIN=$Status,CPIN is Ready" >> $Logfile
			echo "$date:AT+CPIN=$Status,CPIN is Ready" >> $Logfile2
			break
		else
			sleep 3
		fi
	done
	
	if [ "$Status" != "READY" ]
	then
		echo "$date:[AT+CPIN=$Status]CPIN is not Ready" >> $Logfile
		echo "$date:[AT+CPIN=$Status]CPIN is not Ready" >> $Logfile2
		#Reboot/switch sim depending on the interface name.
		ModemReboot $InterfaceName $ComPortSymLink
		
		#Exit if the AddIfaceRunningstatus2 flag is set to 1. 
		CheckAddIfaceRunningstatus2
		
	fi
	
	#To check if it is registered in circuit switched network. should happen within 90 sec.
	#output should be 0,1.
	for i in 1 2 3                                                                                                                  
	do 
		Status=$(/bin/at-cmd "$ComPortSymLink" AT+CREG? | awk NR==2 | cut -d ":" -f 2 | cut -d "," -f 2 | tr -d '\011\012\013\014\015\040')

		if [ $Status = "1" ]
		then
			echo "$date:[AT+CREG?=$Status]Sim is Successfully Registered" >> $Logfile
			echo "$date:[AT+CREG?=$Status]Sim is Successfully Registered" >> $Logfile2
			break
		else
			sleep 3
		fi
	done
	
	if [ "$Status" != "1" ]
	then
		echo "$date:[AT+CREG?=$Status]Sim is not Successfully Registered" >> $Logfile
		echo "$date:[AT+CREG?=$Status]Sim is not Successfully Registered" >> $Logfile2
	fi
	
	#To check if it is registered in circuit switched network. should happen within 90 sec.
	#output should be 0,1.
	for i in 1 2 3                                                                                                                  
	do 
		Status=$(/bin/at-cmd "$ComPortSymLink" AT+CREG? | awk NR==2 | cut -d ":" -f 2 | cut -d "," -f 2 | tr -d '\011\012\013\014\015\040')

		if [ $Status = "1" ]
		then
			echo "$date:[AT+CREG?=$Status]Sim is Successfully Registered" >> $Logfile
			echo "$date:[AT+CREG?=$Status]Sim is Successfully Registered" >> $Logfile2
			break
		else
			sleep 3
		fi
	done
	
	if [ "$Status" != "1" ]
	then
		echo "$date:[AT+CREG?=$Status]Sim is not Successfully Registered" >> $Logfile
		echo "$date:[AT+CREG?=$Status]Sim is not Successfully Registered" >> $Logfile2
	fi
	
	#To check Registration status.
	#output should be 0,1.
	for i in 1 2 3                                                                                                                  
	do 
		Status=$(/bin/at-cmd "$ComPortSymLink" AT+CGREG? | awk NR==2 | cut -d ":" -f 2 | cut -d "," -f 2 | tr -d '\011\012\013\014\015\040')

		if [ $Status = "1" ]
		then
			echo "$date: The sim is registered for AT+CGREG & the status is ="$Status >> $Logfile
			echo "$date: The sim is registered for AT+CGREG & the status is =$Status" >> $Logfile2
			break
		else
			sleep 3
		fi
	done
	
	if [ "$Status" != "1" ]
	then
		echo "$date: The sim is NOT registered for AT+CGREG & the status is ="$Status >> $Logfile
		echo "$date: The sim is 'NOT' registered for AT+CGREG & the status is =$Status" >> $Logfile2
		#Reboot/switch sim depending on the interface name.
		#ModemReboot $InterfaceName $ComPortSymLink
		fi
	
	#Check AT+COPS?
	for i in 1 2                                                                                                                 
	do
		echo "$date: Checking for AT+COPS?" >> $Logfile
		echo "$date: Checking for AT+COPS?" >> $Logfile2
		Status=$(/bin/at-cmd $ComPortSymLink AT+COPS? | sed -n '2p' | tr -d '\011\012\013\014\015\040') 
		
		if [ "$Status" = "+COPS: 0" ]                                                                                                        
		then
			echo "$date: The status of AT+COPS? is $Status. Hence, rebooting ..." >> $Logfile
			echo "$date: The status of AT+COPS? is $Status. Hence, rebooting ..." >> $Logfile2

			#Reboot/switch sim depending on the interface name.
			ModemReboot $InterfaceName $ComPortSymLink
			
			#Exit if the AddIfaceRunningstatus2 flag is set to 1. 
			CheckAddIfaceRunningstatus2
			
			break                                                                                                                     
		elif [ -z "$Status" ]
		then
			echo "$date: The status of AT+COPS? is unavailable. Hence, checking on AltComPort." >> $Logfile
			echo "$date: The status of AT+COPS? is unavailable. Hence, checking on AltComPort." >> $Logfile2
			
			Status_alt=$(/bin/at-cmd $AltComPortSymLink AT+COPS? | sed -n '2p' | tr -d '\011\012\013\014\015\040')
			
			echo "$date: The status of AT+COPS? is $Status_alt." >> $Logfile
			echo "$date: The status of AT+COPS? is $Status_alt." >> $Logfile2
			
			if [ "$Status_alt" = "+COPS: 0" ]                                                                                                        
			then
				echo "$date: The status of AT+COPS? is $Status_alt. Hence, rebooting ..." >> $Logfile
				echo "$date: The status of AT+COPS? is $Status_alt. Hence, rebooting ..." >> $Logfile2

				#Reboot/switch sim depending on the interface name.
				ModemReboot $InterfaceName $AltComPortSymLink
				
				#Exit if the AddIfaceRunningstatus2 flag is set to 1. 
				CheckAddIfaceRunningstatus2
				
				break
			else
				echo "$date: The status of AT+COPS? is $Status_alt." >> $Logfile
				echo "$date: The status of AT+COPS? is $Status_alt." >> $Logfile2
				break
			fi
		else
			echo "$date: The status of AT+COPS? is $Status." >> $Logfile
			echo "$date: The status of AT+COPS? is $Status." >> $Logfile2
			break
		fi
	done 
	
	#Check for the set pdp, APN & authentication.
	for i in 1 2                                                                                         
	do   
	    #check for pdp and apn set in modem ,
	    Status=$(/bin/at-cmd $ComPortSymLink at+cgdcont? | awk NR==2 | awk '{print $2}' | tr -d '\011\012\013\014\015\040')
	    pdp_stat=$(echo $Status | awk -F',' '{print $2}' | awk -F'"' '{print $2}' | tr -d '\011\012\013\014\015\040') 
	    apn_stat=$(echo $Status | awk -F',' '{print $3}' | awk -F'"' '{print $2}' |  tr -d '\011\012\013\014\015\040')

		if [ ! -n "$Status" ]                                                                                                        
		then                                                                                                                           
			sleep 1                                                                                                                     
		else                                                                                                                           
			break                                                                                                                    
		fi                                                                                                                             
	done
	
	#Since we get 1,2,3 in modem config, we change it to ip,ipv6 & ipv4v6. 
	#Because, cgdcont doesn't accept values for pdp. That is, no 1,2,3...
	if [ "$pdp" = "1" ]
	then
		pdp_convert="IP"
	elif [ "$pdp" = "2" ]
	then
		pdp_convert="IPV6"
	elif [ "$pdp" = "3" ]
	then
		pdp_convert="IPV4V6"
	fi
	
	echo "$date: The status obtained by AT+cgdcont? cmd is = "$Status >> $Logfile
	echo "$date: The Default PDP set in modem is = $pdp_stat" >> $Logfile
	echo "$date: The Required PDP is = $pdp_convert" >> $Logfile
	echo "$date: The Default APN set in modem is = $apn_stat" >> $Logfile
	echo "$date: The Required APN is = $APN" >> $Logfile
	
	echo "$date: The status obtained by AT+cgdcont? cmd is = "$Status >> $Logfile2
	echo "$date: The Default PDP set in modem is = $pdp_stat" >> $Logfile2
	echo "$date: The Required PDP is = $pdp_convert" >> $Logfile2
	echo "$date: The Default APN set in modem is = $apn_stat" >> $Logfile2
	echo "$date: The Required APN is = $APN" >> $Logfile2
	
	#If status is empty.
	if [ ! -n "$Status" ]
	then
		echo "$date: The status is empty for AT+cgdcont? cmd." >> $Logfile
		echo "$date: The status is empty for AT+cgdcont? cmd." >> $Logfile2
		#Reboot/switch sim depending on the interface name.
		#ModemReboot $InterfaceName $ComPortSymLink
	fi
	
	#If the pdp, APN & authentication are different, only then, set them using QICSGP command.
	if [ "$pdp_stat" != "$pdp_convert" ] || [ "$apn_stat" != "$APN" ]
	then
		echo "$date: pdp & APN are DIFFERENT." >> $Logfile
		echo "$date: pdp & APN are DIFFERENT." >> $Logfile2
		
		#Set APN
		for i in 1 2                                                                                                                 
		do
			echo "$date: Setting pdp & APN...." >> $Logfile
			echo "$date: Setting pdp & APN...." >> $Logfile2
			
			Status=$(/bin/at-cmd $ComPortSymLink AT+CGDCONT=1,\"$pdp_convert\",\"$APN\",\"\",\"\",\"\" | awk NR==2 | tr -d '\011\012\013\014\015\040') 

			if [ "$Status" = "OK" ]                                                                                                        
			then
				echo "$date: APN & PDP are set Successfully. Hence, Rebooting the modem." >> $Logfile
				echo "$date:  APN & PDP are set Successfully. Hence, Rebooting the modem." >> $Logfile2
				
				sleep 1

				#Reboot/switch sim depending on the interface name.
				ModemReboot $InterfaceName $ComPortSymLink
				
				#Exit if the AddIfaceRunningstatus2 flag is set to 1. 
				CheckAddIfaceRunningstatus2
				
				break                                                                                                                     
			else                                                                                                                           
				sleep 3                                                                                                                    
			fi                                                                                                                           
		done 
		
		if [ "$Status" != "OK" ]
		then
			echo "$date:AT+cgdcont? command Status is $Status, status not OK when apn,pdp is not set Successfully" >> $Logfile
			echo "$date:AT+cgdcont? command Status is $Status, status not OK when apn,pdp is not set Successfully" >> $Logfile2
			
			#Reboot/switch sim depending on the interface name.
			ModemReboot $InterfaceName $ComPortSymLink
			
			#Exit if the AddIfaceRunningstatus2 flag is set to 1. 
			CheckAddIfaceRunningstatus2
		fi

	#If the pdp, APN & authentication are same.
	else
		#Activate pdp context 1. Get response -- either OK/Error.
		for i in 1 2 3                                                                                                                    
		do
			Status=$(/bin/at-cmd $ComPortSymLink AT+QIACT=1 | awk NR==2 | tr -d '\011\012\013\014\015\040')
									 
			if [ "$Status" = "OK" ]                                                                                                        
			then
				echo "$date: pdp & APN are SAME." >> $Logfile
				echo "$date: pdp & APN are SAME." >> $Logfile2
				break                                                                                                                     
			else                                                                                                                           
				sleep 3                                                                                                                    
			fi                                                                                                                             
		done 
		
		#If the response of AT+QIACT=1 is error or if it has no response.
		if [ "$Status" != "OK" ]
		then
			echo "$date: The status of AT+QIACT=1 cmd is not OK & it is = "$Status >> $Logfile
			echo "$date: The status of AT+QIACT=1 cmd is not OK & it is = "$Status >> $Logfile2
			
			#echo "AT+QIDEACT=1 Deactivate the pdp context." >> $Logfile
			#Deactivate and then reboot
			#/bin/at-cmd $ComPortSymLink AT+QIDEACT=1
			#sleep 1
			#Reboot/switch sim depending on the interface name.
			#ModemReboot $InterfaceName $ComPortSymLink
			
		#If the response of AT+QIACT=1 is OK
		else
			#check if pdp is activated/not.
			for i in 1 2 3                                                                                                                    
			do	
				#To get only IP we use here (cut -d "," -f 4)
				Status=$(/bin/at-cmd $ComPortSymLink AT+QIACT? | awk NR==2 | cut -d "," -f 4 | tr -d '\011\012\013\014\015\040')
				Status=$(echo $Status | tr -d '"')
				echo "$date: The status of AT+QIACT? cmd is = $Status" >> $Logfile
				echo "$date: The status of AT+QIACT? cmd is = $Status" >> $Logfile2
				
				#For ipv4 -
				if [ "$pdp" = "1" ]
				then
					ipaddr_obtained=$(echo $Status | cut -d "," -f 4 | tr -d '\011\012\013\014\015\040')
					ipaddr=$(echo $Status | cut -d "," -f 4 | tr -d -c '.' | wc -c | tr -d '\011\012\013\014\015\040')				
					
					echo "$date: The IP address is - $ipaddr_obtained" >> $Logfile
					echo "$date: The IP address is - $ipaddr_obtained" >> $Logfile2
					
					#ipv4 has 3 dots (.)                         
					if [ "$ipaddr" = "3" ]                                                                                                        
					then
						echo "$date: It's an IPV4 address." >> $Logfile
						echo "$date: It's an IPV4 address." >> $Logfile2
						break
					else
						echo "$date: The IPv4 address obtained is incorrect. It has '$ipaddr' dots." >> $Logfile
						echo "$date: The IPv4 address obtained is incorrect. It has '$ipaddr' dots." >> $Logfile2
						#Reboot/switch sim depending on the interface name.
						#ModemReboot $InterfaceName $ComPortSymLink
					fi
				
				#For ipv6 -
				elif [ "$pdp" = "2" ]
				then
				
					ipaddr_obtained=$(echo $Status | cut -d "," -f 4 | tr -d '\011\012\013\014\015\040')
					ipaddr=$(echo $Status | cut -d "," -f 4 | cut -d ":" -f 1 | awk -F'"' '{print $2}' | tr -d '\011\012\013\014\015\040')
					
					echo "$date: The IP address is - $ipaddr_obtained" >> $Logfile
					echo "$date: The IP address is - $ipaddr_obtained" >> $Logfile2
					
					#ipv6 starting addr should be greater then 2000                         
					if [ "$ipaddr" -gt "2000" ]                                                                                                        
					then
						echo "$date: It's an IPV6 address." >> $Logfile
						echo "$date: It's an IPV6 address." >> $Logfile2
						break
					else
						echo "$date: The IPv6 address obtained is incorrect. It has '$ipaddr' starting address." >> $Logfile
						echo "$date: The IPv6 address obtained is incorrect. It has '$ipaddr' starting address." >> $Logfile2
						#Reboot/switch sim depending on the interface name.
						#ModemReboot $InterfaceName $ComPortSymLink
					fi
				
				#For ipv4v6 -
				elif [ "$pdp" = "3" ]
				then
					
					Status=$(at-cmd "$ComPortSymLink" at+cgpaddr=1 | tr -d '\011\012\013\014\015\040')
					
					#For ipv4 address					
					ipaddr1=$(echo $Status | cut -d "," -f 2 | tr -d -c '.' | wc -c | tr -d '\011\012\013\014\015\040')

					# Extracting the IPv6 address in decimal format
					ipv6_decimal=$(echo $Status | cut -d "," -f 3)

					# Extracting the first two numbers of the decimal IPv6 address
					first_two_numbers_decimal=$(echo $ipv6_decimal | cut -d "." -f 1-2)

					# Converting the decimal numbers to hexadecimal
					ipaddr2=$(echo $first_two_numbers_decimal | awk '{ printf "%02X%02X", $1, $2 }')
					
					#ipv6 starting addr should be greater then 2000 & ipv4 has 3 dots (.)                        
					if [ "$ipaddr1" = "3" ] && [ "$ipaddr2" -gt "2000" ]                                                
					then
						echo "$date: It's an IPV4V6 address" >> $Logfile
						echo "$date: It's an IPV4V6 address" >> $Logfile2
						break
					else
						echo "$date: The IPv6 address obtained is incorrect. It has '$ipaddr1' dots & '$ipaddr2' starting address." >> $Logfile
						echo "$date: The IPv6 address obtained is incorrect. It has '$ipaddr1' dots & '$ipaddr2' starting address." >> $Logfile2
						#Reboot/switch sim depending on the interface name.
						#ModemReboot $InterfaceName $ComPortSymLink
					fi
				
				#For wrong pdp
				else
					echo "$date: Wrong pdp set. Rebooting ..." >> $Logfile
					echo "$date: Wrong pdp set. Rebooting ..." >> $Logfile2
					#Reboot/switch sim depending on the interface name.
					ModemReboot $InterfaceName $ComPortSymLink
					
					#Exit if the AddIfaceRunningstatus2 flag is set to 1. 
					CheckAddIfaceRunningstatus2
				fi                                                                                                                         
			done
		fi
	fi
}

#
# Input arguments and Default Parameters
#
InterfaceName="$1"
ModemConfigFile="/etc/config/modem"
ScriptStatustDir="/tmp/InterfaceManager/status"
ScriptLogDir="/tmp/InterfaceManager/log"
PortDetailsFile="$ScriptStatustDir/$InterfaceName"".ports"
AddIfaceStatusFile="$ScriptStatustDir/$InterfaceName"".AddIfaceStatus"
DeleteStatusFile="$ScriptStatustDir/$InterfaceName"".DeleteIfaceStatus"
lockfile="/var/run/$InterfaceName""AddIface.lockfile"
SleepAfterIfdown=2
SleepForEnumerationOfAllPorts=7
SystemConfigFile="/etc/config/sysconfig"
SystemGpioConfig="/etc/config/systemgpio"
QccidScript="/etc/gcom/getcardqccidinfo.gcom"
SetnetDev="/etc/gcom/setnetdev.gcom"
GetnetDev="/etc/gcom/getnetdev.gcom"
SetApn="/etc/gcom/setapn.gcom"
SetRawIp="/etc/gcom/setrawip.gcom"
SetQiAct="/etc/gcom/setqiact.gcom"
GetQiAct="/etc/gcom/getqiact.gcom"

CountNumFile="/tmp/CountNumFile"
SimNumFile="/tmp/simnumfile"

[ -d "$ScriptStatustDir" ]  || mkdir -p "$ScriptStatustDir"
[ -d "$ScriptLogDir" ]  || mkdir -p "$ScriptLogDir"

date=$(date)
LogrotateConfigFile="/etc/logrotate.d/AddInterfaceLogrotateConfig"
Logfile="/root/ConfigFiles/Logs/AddInterfaceLogs.txt"
LogrotateConfigFile1="/etc/logrotate.d/alllogsmod1"
Logfile1="/root/ConfigFiles/Logs/all_logs_mod1.txt"
#Logfile1="/tmp/all_logs_mod1.txt"
LogrotateConfigFile2="/etc/logrotate.d/alllogsmod2"
Logfile2="/root/ConfigFiles/Logs/all_logs_mod2.txt"
#Logfile2="/tmp/all_logs_mod2.txt"

Updatebandlock="/root/InterfaceManager/script/Bandlock.sh"
Updateoperatorlock="/root/InterfaceManager/script/operatorlock.sh"
CheckUpdateoperatorlock="/root/InterfaceManager/script/check_operatorlock.sh"

#
# verify input arguments
#
if [ "x$InterfaceName" = "x" ]
then
        echo "Usage: $0 InterfaceName"
        echo "status=Invalid interface" > "$AddIfaceStatusFile"
        exit 1
fi

#Exit if the AddIfaceRunningstatus2 flag is set to 1. 
source /tmp/AddIfaceRunningstatus2
if [ "$AddIfaceRunningstatus2" = "1" ] 
then 
    exit 0
fi

echo " " >> $Logfile2
echo "----------<AddInterface_mod2.sh> -----------" >> $Logfile2


# Function to check if the lock file is present and wait until it's removed
wait_for_lock() {
  while [ -e "$lockfile" ]; do
    echo "<AddInterface_mod2.sh> Lock file ($lockfile) exists..." >> $Logfile2
    echo "<AddInterface_mod2.sh> killing the $lockfile" >> $Logfile2
	
	rm -f "$lockfile"
	
    sleep 1
  done
}

# Check if the lock file is present and wait until it's removed
wait_for_lock

if (set -o noclobber; echo $$ > "$lockfile") 2> /dev/null
then
	trap 'rm -f "$lockfile"; exit $?' INT TERM EXIT

	ReadModemConfigFile
	ReadSystemConfigFile
	ReadSystemGpioFile
	
	echo "<AddInterface_mod2.sh> Removed lockfile=$lockfile " >> $Logfile2
	
	if [ "$ModemEnable" -ne 1 ]
	then
		rm -f "$PortDetailsFile"
		rm -f "$AddIfaceStatusFile"
		exit 0
	fi
	rm -f "$DeleteStatusFile"
	
	#IPV6 or IPV4V6
	if [ "$InterfaceName" = "CWAN1_0" ] || [ "$InterfaceName" = "CWAN1" ]
	then
		IPV6InterfaceName="wan6c1"
		ifdown "$IPV6InterfaceName" > /dev/null 2>&1
	elif [ "$InterfaceName" = "CWAN1_1" ] || [ "$InterfaceName" = "CWAN2" ]
	then
		IPV6InterfaceName="wan6c2"
		ifdown "$IPV6InterfaceName" > /dev/null 2>&1
	fi

	if [ "$CellularOperationModelocal" = "dualcellularsinglesim" ]
	then
		if [ "$InterfaceName" = "CWAN1" ]
		then
			uci delete network.wan6c1 > /dev/null 2>&1
			#Delete the xlat from network config file.
			uci delete network.wan6c1_xlat > /dev/null 2>&1
		else
			uci delete network.wan6c2 > /dev/null 2>&1
			#Delete the xlat from network config file.
			uci delete network.wan6c2_xlat > /dev/null 2>&1
		fi
	#singlecellulardualsim & singlecellularsinglesim
	else 
		uci delete network.wan6c1 > /dev/null 2>&1
		uci delete network.wan6c2 > /dev/null 2>&1
		#Delete the xlat from network config file.
		uci delete network.wan6c1_xlat > /dev/null 2>&1
		uci delete network.wan6c2_xlat > /dev/null 2>&1
	fi
	uci commit network
	
	PortSearch $InterfaceName $ConfiguredComPort $IPV6InterfaceName
	
	/bin/sleep 3	
	
	#Exit if the AddIfaceRunningstatus2 flag is set to 1. 
	CheckAddIfaceRunningstatus2

	echo "<AddInterface_mod2.sh> qnetdevctl.sh triggered with $ComPortSymLink for $InterfaceName. " >> $Logfile2
	
	/bin/qnetdevctl.sh $ComPortSymLink $InterfaceName "qnetdevctl2" &
	
	rm -f "$lockfile"
	trap - INT TERM EXIT

fi

#create this for mwan3 restart in /bin/mwan3script.sh
touch /tmp/add2_flag
# Store the process ID
echo $$ > /tmp/add2_pid

#Run Check operatorlock script 
    $CheckUpdateoperatorlock "AddInterface_mod2"  
    
#For routerlocalpingapp.
echo "AddIfaceRunningstatus2=0" > /tmp/AddIfaceRunningstatus2

#For snmp agent Modem2_Output.sh script is run to get the basic information of Modem.
/bin/snmp/Modem2_Output.sh &

logrotate "$LogrotateConfigFile"
logrotate "$LogrotateConfigFile1"
logrotate "$LogrotateConfigFile2"

exit 0
