#!/bin/sh /etc/rc.common
# Copyright (C) 2013-2014 OpenWrt.org

START=00
STOP=90

RTC_DEV=/dev/rtc0
HWCLOCK=/sbin/hwclock

#source /etc/FirstBootStatus
#if [ "$FirstBootStatus" = "0" ]
#then

	#while true
	#do
		## Copy the network file to both backup and check folders.
		#cp /etc/config/network /etc/inv_eth/network_backup/
		#cp /etc/config/network /etc/inv_eth/network_check/

		## Check if both the network files are the same.
		#if cmp -s /etc/inv_eth/network_backup/network /etc/inv_eth/network_check/network
		#then
			## Copy the single port network config to the original network config location.
			#cp /etc/inv_eth/single_port/network /etc/config/

			## Check if the copied file matches the expected single port network config.
			#if cmp -s /etc/inv_eth/single_port/network /etc/config/network
			#then
				#break
			#fi
		#fi
		
		#sleep 1
	#done
#fi

boot() {
	start && exit 0

	local maxtime="$(maxtime)"
	local curtime="$(date +%s)"
	[ $curtime -lt $maxtime ] && date -s @$maxtime
}

start() {
	[ -e "$RTC_DEV" ] && [ -e "$HWCLOCK" ] && $HWCLOCK -s -u -f $RTC_DEV
}

stop() {
	[ -e "$RTC_DEV" ] && [ -e "$HWCLOCK" ] && $HWCLOCK -w -u -f $RTC_DEV && \
		logger -t sysfixtime "saved '$(date)' to $RTC_DEV"
}

maxtime() {
	local file newest

	for file in $( find /etc -type f ) ; do
		[ -z "$newest" -o "$newest" -ot "$file" ] && newest=$file
	done
	[ "$newest" ] && date -r "$newest" +%s
}
