#!/bin/sh
# Copyright (C) 2015 PIVA Software <www.pivasoftware.com>
# 	Author: MOHAMED Kallel <mohamed.kallel@pivasoftware.com>

#common_execute_method_param "$parameter" "$permission" "$get_cmd" "$set_cmd" "xsd:$type" "$forcedinform"
#  $forcedinform should be set to 1 if the parameter is included in the inform message otherwise empty
#  Default of $type = string

#############################
#   Entry point functuons   #
#############################

prefix_list="$prefix_list $DMROOT.DeviceInfo."
entry_execute_method_list="$entry_execute_method_list entry_execute_method_root_DeviceInfo"
entry_execute_method_list_forcedinform="$entry_execute_method_list_forcedinform  entry_execute_method_root_DeviceInfo"

########################
#RSSI
Servingcell=$(/bin/at-cmd /dev/ttyUSB1 at+qeng="servingcell" | awk -F"," 'NR==2') 

MCC=$(echo $Servingcell | awk -F"," 'NR==1 {print$5}')
MNC=$(echo $Servingcell | awk -F"," 'NR==1 {print$6}')
UBW=$(echo $Servingcell | awk -F"," 'NR==1 {print$11}')
DBW=$(echo $Servingcell | awk -F"," 'NR==1 {print$12}')

########################################################################
ComPort=$(uci get sysconfig.sysconfig.ComPortSymLink1)
Quality_Signal_Noise_Full=$(gcom -d "$ComPort" -s /etc/gcom/getquality.gcom)
Connected_LTE=$(echo "$Quality_Signal_Noise_Full" | grep -o LTE | tr -d '\011\012\013\014\015\040')
Connected_NSA=$(echo "$Quality_Signal_Noise_Full" | grep -o NR5G-NSA | tr -d '\011\012\013\014\015\040')
Connected_SA=$(echo "$Quality_Signal_Noise_Full" | grep -o NR5G-SA | tr -d '\011\012\013\014\015\040')
if [ "$Connected_LTE" = "LTE" ] && [ "$Connected_NSA" = "NR5G-NSA" ]
then
	Connected="NSA"
	Quality_Signal_Noise1=$(echo "$Quality_Signal_Noise_Full" | awk NR==3)
	Quality_Signal_Noise2=$(echo "$Quality_Signal_Noise_Full" | awk NR==4)

elif [ "$Connected_LTE" = "LTE" ]
then
	Connected="LTE"
	Quality_Signal_Noise=$(echo "$Quality_Signal_Noise_Full" | awk NR==2)
	
elif [ "$Connected_SA" = "NR5G-SA" ]
then
	Connected="SA"
	Quality_Signal_Noise=$(echo "$Quality_Signal_Noise_Full" | awk NR==2)
fi
if [ "$Connected" = "SA" ] 
then
	RSRP=$(echo "$Quality_Signal_Noise" | cut -d "," -f 13 | tr -d '\011\012\013\014\015\040')
	RSRQ=$(echo "$Quality_Signal_Noise" | cut -d "," -f 14 | tr -d '\011\012\013\014\015\040')
	RSSI="-"
	SINR=$(echo "$Quality_Signal_Noise" | cut -d "," -f 15 | tr -d '\011\012\013\014\015\040')
elif [ "$Connected" = "LTE" ] 
then
	RSRP=$(echo "$Quality_Signal_Noise" | cut -d "," -f 14 | tr -d '\011\012\013\014\015\040')
	RSRQ=$(echo "$Quality_Signal_Noise" | cut -d "," -f 15 | tr -d '\011\012\013\014\015\040')
	RSSI=$(echo "$Quality_Signal_Noise" | cut -d "," -f 16 | tr -d '\011\012\013\014\015\040')
	SINR=$(echo "$Quality_Signal_Noise" | cut -d "," -f 17 | tr -d '\011\012\013\014\015\040')
elif [ "$Connected" = "NSA" ]
then
	band=$(at-cmd "$ComPort" at+qnwinfo | grep -i "NSA" | cut -d "," -f 3)
	RSRP=$(echo "$Quality_Signal_Noise2" | cut -d "," -f 5 | tr -d '\011\012\013\014\015\040')
	if [ "$band" = "\"\"" ] || [ "$band" = "\" \"" ] && [ $RSRP -eq 0 ] 
	then
		RSRP=$(echo "$Quality_Signal_Noise1" | cut -d "," -f 12 | tr -d '\011\012\013\014\015\040')
		RSRQ=$(echo "$Quality_Signal_Noise1" | cut -d "," -f 13 | tr -d '\011\012\013\014\015\040')
		RSSI=$(echo "$Quality_Signal_Noise1" | cut -d "," -f 14 | tr -d '\011\012\013\014\015\040')
		SINR=$(echo "$Quality_Signal_Noise1" | cut -d "," -f 15 | tr -d '\011\012\013\014\015\040')
	else
		RSRP=$(echo "$Quality_Signal_Noise2" | cut -d "," -f 5 | tr -d '\011\012\013\014\015\040')
		RSRQ=$(echo "$Quality_Signal_Noise2" | cut -d "," -f 7 | tr -d '\011\012\013\014\015\040')
		RSSI=$(echo "$Quality_Signal_Noise1" | cut -d "," -f 14 | tr -d '\011\012\013\014\015\040')
		SINR=$(echo "$Quality_Signal_Noise2" | cut -d "," -f 6 | tr -d '\011\012\013\014\015\040')
	fi
else
	RSSI=$(at-cmd "$ComPort" at+csq | grep +CSQ | cut -d " " -f 2 | cut -d "," -f 1 | tr -d '\011\012\013\014\015\040')
	RSSI=$((31-RSSI))
	RSSI=$((RSSI*2))
	RSSI=$((-51-RSSI))
fi
########################################################################

UPTIME=$(awk -F '.' '{ print $1 }' /proc/uptime)
UPTIME_MIN=$((UPTIME/60))
UPTIME_SEC=$((UPTIME%60))
firmware_version=$(uci get boardconfig.board.FirmwareVer)
#######################

entry_execute_method_root_DeviceInfo() {
	case "$1" in ""|"$DMROOT."|"$DMROOT.DeviceInfo."*)
		common_execute_method_obj "$DMROOT.DeviceInfo." "0"
		common_execute_method_param "$DMROOT.DeviceInfo.SpecVersion" "0" "echo 1.0" "" "" "1"
		common_execute_method_param "$DMROOT.DeviceInfo.ProvisioningCode" "1" "$UCI_GET easycwmp.@local[0].provisioning_code" "device_info_set_provisioningcode" "" "1"
		common_execute_method_param "$DMROOT.DeviceInfo.Manufacturer" "0" "echo INVENDIS" "" "" "1"
		common_execute_method_param "$DMROOT.DeviceInfo.ManufacturerOUI" "0" "$UCI_GET easycwmp.@device[0].oui" "" "" "1"
		common_execute_method_param "$DMROOT.DeviceInfo.ProductClass" "0" "echo Test-Router" "" "" "1"
		common_execute_method_param "$DMROOT.DeviceInfo.SerialNumber" "0" "$UCI_GET easycwmp.@device[0].serial_number" "" "" "1"
		common_execute_method_param "$DMROOT.DeviceInfo.HardwareVersion" "0" "$UCI_GET easycwmp.@device[0].hardware_version" "" "" "1"
		common_execute_method_param "$DMROOT.DeviceInfo.SoftwareVersion" "0" "$UCI_GET easycwmp.@device[0].software_version" "" "" "1"
		common_execute_method_param "$DMROOT.DeviceInfo.RSSI" "0" "echo $RSSI" "" "" "1"
		common_execute_method_param "$DMROOT.DeviceInfo.UpTime" "0" "echo {$UPTIME_MIN min:$UPTIME_SEC sec}" "" "xsd:unsignedInt"
		common_execute_method_param "$DMROOT.DeviceInfo.DeviceLog" "0" "echo $(dmesg | tail -n1)"
		common_execute_method_obj "$DMROOT.DeviceInfo.MemoryStatus." "0"
		common_execute_method_param "$DMROOT.DeviceInfo.MemoryStatus.Total" "0" "device_info_get_total_memory"
		common_execute_method_param "$DMROOT.DeviceInfo.MemoryStatus.Free" "0" "device_info_get_free_memory"
		common_execute_method_param "$DMROOT.DeviceInfo.MCC" "0" "echo $MCC" "" "" "1"
		common_execute_method_param "$DMROOT.DeviceInfo.MNC" "0" "echo $MNC" "" "" "1"  
		common_execute_method_param "$DMROOT.DeviceInfo.UBW" "0" "echo $UBW" "" "" "1"  
		common_execute_method_param "$DMROOT.DeviceInfo.DBW" "0" "echo $DBW" "" "" "1"  
		common_execute_method_param "$DMROOT.DeviceInfo.RSRP" "0" "echo $RSRP" "" "" "1"  
		common_execute_method_param "$DMROOT.DeviceInfo.RSRQ" "0" "echo $RSRQ" "" "" "1"  
		common_execute_method_param "$DMROOT.DeviceInfo.SINR" "0" "echo $SINR" "" "" "1"    
		common_execute_method_param "$DMROOT.DeviceInfo.Firmware_Version" "0" "echo $firmware_version" "" "" "1"        
		return 0;
		;;
	esac
	return $E_INVALID_PARAMETER_NAME;
}

#######################################
#   Data model parameters functions   #
#######################################

device_info_get_total_memory() {
		cut -d: -f 2 /proc/meminfo | head -n 1| tail -n 1 |  tr -d " kKbB"
}

device_info_get_free_memory() {
		cut -d: -f 2 /proc/meminfo | head -n 2| tail -n 1 | tr -d " kKbB" 
}

device_info_set_provisioningcode() {
	local val="$1"
	$UCI_SET easycwmp.@local[0].provisioning_code="$val"
	return 0
}

device_info_get_uptime() {
	awk -F '.' '{ print $1 }' /proc/uptime
}
