#!/bin/sh

. /lib/functions.sh
sleep 5

#To check if the firstboot script got executed.
echo "FirstBootStatus=1" > /etc/FirstBootStatus

#For new user sshadmin
chown sshadmin /root
chown sshadmin /root/user
chown sshadmin /root/user/init.d

#Read mac addr
RunReadMacaddr()
{

	#serialnumber
	serial_n=$(hexdump -v -n 6 -s 0xe030 -e '5/1 "%02X:" 1/1 "%02X"' /dev/mtd2 | sed 's/://g')
	serial_number="${serial_n:1}"

	#imei
	imei_n1=$(hexdump -v -n 8 -s 0xe040 -e '7/1 "%02X:" 1/1 "%02X"' /dev/mtd2 | sed 's/://g')
	imei1="${imei_n1:1}"
	imei_n2=$(hexdump -v -n 8 -s 0xe050 -e '7/1 "%02X:" 1/1 "%02X"' /dev/mtd2 | sed 's/://g')
	imei2="${imei_n2:1}"

	#wan
	wan_mac_addr=$(hexdump -v -n 6 -s 0xe000 -e '5/1 "%02X:" 1/1 "%02X"' /dev/mtd2)

	#lan
	lan1_mac_addr=$(hexdump -v -n 6 -s 0xe006 -e '5/1 "%02X:" 1/1 "%02X"' /dev/mtd2)
	lan2_mac_addr=$(hexdump -v -n 6 -s 0xe00c -e '5/1 "%02X:" 1/1 "%02X"' /dev/mtd2)
	lan3_mac_addr=$(hexdump -v -n 6 -s 0xe012 -e '5/1 "%02X:" 1/1 "%02X"' /dev/mtd2)
	lan4_mac_addr=$(hexdump -v -n 6 -s 0xe018 -e '5/1 "%02X:" 1/1 "%02X"' /dev/mtd2)

	#wlan0 
	wifi2ghz_mac_addr=$(hexdump -v -n 6 -s 0x0004 -e '5/1 "%02X:" 1/1 "%02X"' /dev/mtd2)
	#wlan1 
	wifi5ghz_mac_addr=$(hexdump -v -n 6 -s 0x8004 -e '5/1 "%02X:" 1/1 "%02X"' /dev/mtd2)

	sleep 1

	echo " " > /etc/config/factorymacaddr

	#Add macaddr to factorymacaddr config file.
	echo $wan_mac_addr >> /etc/config/factorymacaddr
	echo $lan1_mac_addr >> /etc/config/factorymacaddr
	echo $lan2_mac_addr >> /etc/config/factorymacaddr
	echo $lan3_mac_addr >> /etc/config/factorymacaddr
	echo $lan4_mac_addr >> /etc/config/factorymacaddr

	echo " " > /etc/config/macaddr

	#Add macaddr to macaddr config file.
	echo $wan_mac_addr >> /etc/config/macaddr
	echo $lan1_mac_addr >> /etc/config/macaddr
	echo $lan2_mac_addr >> /etc/config/macaddr
	echo $lan3_mac_addr >> /etc/config/macaddr
	echo $lan4_mac_addr >> /etc/config/macaddr

	sleep 1

	#uci set system.system.hostname=$serial_number
	#uci set sysconfig.sysconfig.port1macid=$lan1_mac_addr
	#uci set sysconfig.sysconfig.port2macid=$lan2_mac_addr
	#uci set sysconfig.sysconfig.port3macid=$lan3_mac_addr
	#uci set sysconfig.sysconfig.port4macid=$lan4_mac_addr
	#uci set sysconfig.sysconfig.port5macid=$wan_mac_addr
	#uci set sysconfig.sysconfig.wifi2ghzmacid=$wifi2ghz_mac_addr
	#uci set sysconfig.sysconfig.wifi5ghzmacid=$wifi5ghz_mac_addr
	#uci set sysconfig.sysconfig.imei=$imei1
	#uci set sysconfig.sysconfig.imei2=$imei2
	uci set wireless.rai0_ap.macaddr=$wifi5ghz_mac_addr

	#According to board name we set ssid .
	model_path="/tmp/sysinfo/model"
	board_name=$(cat "$model_path" | sed 's/Invendis Silbo-//g')

	sleep 1

	#ssid

	wirelessdatfile="/etc/wireless/mt7615/mt7615.1.dat"

	wifissid_2="${board_name}_${serial_number}_2.4"
	wifissid_5="${board_name}_${serial_number}_5"

	uci set sysconfig.wificonfig.wifi1ssid=${wifissid_2}
	uci set sysconfig.wificonfig.wifi5ssid=${wifissid_5}

	uci set wireless.ra0_ap.ssid=${wifissid_2}

	uci set wireless.rai0_ap.ssid=${wifissid_5}
	 
	ssid=$(grep -w "SSID1" ${wirelessdatfile})        

	ssid_replace="SSID1=$wifissid_2"

	sed -i "s/${ssid}/${ssid_replace}/" "$wirelessdatfile"

	#update serial number,firmware version,wifi ssid in easycwmp config file

	Firmwareversion=$(uci get boardconfig.board.FirmwareVer)
	Applicationversion=$(uci get boardconfig.board.ApplicationSwVer)
	wifi_passwd=$(uci get sysconfig.wificonfig.wifi1key)
	Model=$(uci get boardconfig.board.model)
	#Get starting 3 values of mac addr without ":"
	var=${wan_mac_addr:0:8}
	OUI=$( echo $var | sed 's/://g' )

	uci set easycwmp.@device[0].serial_number=$serial_number
	uci set easycwmp.@device[0].software_version=${Firmwareversion}_${Applicationversion}
	uci set easycwmp.@device[0].product_class=$Model
	uci set easycwmp.@device[0].oui=$OUI

	uci set remote.tr.ssid=$wifissid_2
	uci set remote.tr.passwd=$wifi_passwd

	uci commit wireless
	uci commit easycwmp
	uci commit remote
	uci commit system
	uci commit sysconfig

	sleep 1

	/etc/init.d/system restart > /dev/null 2>&1

	sleep 1

	cp /etc/config/* /root/InterfaceManager/config

	/root/InterfaceManager/script/Port_Based_Vlan.sh

	sleep 1

	/root/InterfaceManager/script/Network_Interface.sh
}

#Read mac addr
RunReadMacaddr_RN50()
{

	#serialnumber
	serial_n=$(hexdump -v -n 6 -s 0xe030 -e '5/1 "%02X:" 1/1 "%02X"' /dev/mtd2 | sed 's/://g')
	serial_number="${serial_n:1}"

	#wan
	wan_mac_addr=$(hexdump -v -n 6 -s 0xe000 -e '5/1 "%02X:" 1/1 "%02X"' /dev/mtd2)

	#lan
	lan1_mac_addr=$(hexdump -v -n 6 -s 0xe006 -e '5/1 "%02X:" 1/1 "%02X"' /dev/mtd2)

	#wlan0 
	wifi2ghz_mac_addr=$(hexdump -v -n 6 -s 0x0004 -e '5/1 "%02X:" 1/1 "%02X"' /dev/mtd2)
	#wlan1 
	wifi5ghz_mac_addr=$(hexdump -v -n 6 -s 0x8004 -e '5/1 "%02X:" 1/1 "%02X"' /dev/mtd2)

	uci set boardconfig.board.serialnum=$serial_number
	uci set boardconfig.board.macaddress1=$wan_mac_addr
	uci set boardconfig.board.macaddress2=$lan1_mac_addr
	uci set boardconfig.board.wifi2ghzmacid=$wifi2ghz_mac_addr
	uci set boardconfig.board.wifi5ghzmacid=$wifi5ghz_mac_addr
	uci commit boardconfig

	sleep 1

	echo " " > /etc/config/factorymacaddr

	#Add macaddr to factorymacaddr config file.
	echo $wan_mac_addr >> /etc/config/factorymacaddr
	echo $lan1_mac_addr >> /etc/config/factorymacaddr

	echo " " > /etc/config/macaddr

	#Add macaddr to macaddr config file.
	echo $wan_mac_addr >> /etc/config/macaddr
	echo $lan1_mac_addr >> /etc/config/macaddr
	sleep 1

	uci set system.system.hostname=$serial_number
	uci set sysconfig.sysconfig.port1macid=$lan1_mac_addr
	uci set sysconfig.sysconfig.port5macid=$wan_mac_addr
	uci set sysconfig.sysconfig.wifi2ghzmacid=$wifi2ghz_mac_addr
	uci set sysconfig.sysconfig.wifi5ghzmacid=$wifi5ghz_mac_addr
	uci set wireless.rai0_ap.macaddr=$wifi5ghz_mac_addr

	board_name=$(uci get boardconfig.board.boardname | cut -d "-" -f2)

	sleep 1

	#ssid

	wirelessdatfile="/etc/wireless/mt7615/mt7615.1.dat"

	wifissid_2="${board_name}_${serial_number}_2.4"
	wifissid_5="${board_name}_${serial_number}_5"

	uci set sysconfig.wificonfig.wifi1ssid=${wifissid_2}
	uci set sysconfig.wificonfig.wifi5ssid=${wifissid_5}

	uci set wireless.ra0_ap.ssid=${wifissid_2}

	uci set wireless.rai0_ap.ssid=${wifissid_5}
	 
	ssid=$(grep -w "SSID1" ${wirelessdatfile})        

	ssid_replace="SSID1=$wifissid_2"

	sed -i "s/${ssid}/${ssid_replace}/" "$wirelessdatfile"

	#update serial number,firmware version,wifi ssid in easycwmp config file

	Firmwareversion=$(uci get boardconfig.board.FirmwareVer)
	Applicationversion=$(uci get boardconfig.board.ApplicationSwVer)
	wifi_passwd=$(uci get sysconfig.wificonfig.wifi1key)
	Model=$(uci get boardconfig.board.model)
	#Get starting 3 values of mac addr without ":"
	var=${wan_mac_addr:0:8}
	OUI=$( echo $var | sed 's/://g' )

	uci set easycwmp.@device[0].serial_number=$serial_number
	uci set easycwmp.@device[0].software_version=${Firmwareversion}_${Applicationversion}
	uci set easycwmp.@device[0].product_class=$Model
	uci set easycwmp.@device[0].oui=$OUI

	uci set remote.tr.ssid=$wifissid_2
	uci set remote.tr.passwd=$wifi_passwd

	uci commit wireless
	uci commit easycwmp
	uci commit remote
	uci commit system
	uci commit sysconfig

	sleep 1

	/etc/init.d/system restart > /dev/null 2>&1

	sleep 1

	cp /etc/config/* /root/InterfaceManager/config

	/root/InterfaceManager/script/Port_Based_Vlan.sh

	sleep 1

	/root/InterfaceManager/script/Network_Interface.sh
}

#get the board name from Sysinfo 
board_name=$(cat /tmp/sysinfo/board_name | cut -d "," -f2)
#Create a text file to store the board name  
touch /root/Web_page/Board_info.txt
#store the board name to the newly created text file
echo "board_name=$board_name" > /root/Web_page/Board_info.txt
source /root/Web_page/Board_info.txt
#Get only product name 
RS_Product_name=$(echo $board_name | grep -o RS)
RQ_Product_name=$(echo $board_name | grep -o RQ)
RK_Product_name=$(echo $board_name | grep -o RK)
RU_Product_name=$(echo $board_name | grep -o RU)
RV00_Product_name=$(echo $board_name | grep -o RV00)
RV04_Product_name=$(echo $board_name | grep -o RV04)
RV54_1_Product_name=$(echo $board_name | grep -o RV54-1)
RV54_2_Product_name=$(echo $board_name | grep -o RV54-2)
RVW50_Product_name=$(echo $board_name | grep -o RVW50)
RG_Product_name=$(echo $board_name | grep -o RG)
ID_Product_name=$(echo $board_name | grep -o ID)
RN50_Product_name=$(echo $board_name | grep -o RN50)

#retain and config
retain=$(uci get applist_config.appconfig.retain)
if [ "$retain" = "1" ]
then
	#removed  
	rm -rf /Web_page
else
	echo "default packages has been added"
	echo "it will not retain the previous config"
fi

#copying all the config files, banner and the network.js for ui using 
if [ "$RS_Product_name" = "RS" ]
then
	echo "Product_name = RS"
	Product_name="RS"
	cp /Web_page/RS/etc/banner /etc/
	cp /Web_page/RS/etc/config/* /etc/config/
	cp -r /Web_page/RS/usr/local/bin/* /usr/local/bin/
	cp /Web_page/RS/root/InterfaceManager/script/* /root/InterfaceManager/script/
	cp /Web_page/RS/usr/libexec/rpcd/* /usr/libexec/rpcd/
	cp /Web_page/RS/www/luci2/view/* /www/luci2/view/ 
	cp /www/luci2/view/modemstatus2 /www/luci2/view/diagnostics.modemstatus.js
elif [ "$RQ_Product_name" = "RQ" ] 
then
	echo "Product_name = RQ"
	Product_name="RQ"
	cp /Web_page/RQ/etc/banner /etc/
	cp /Web_page/RQ/etc/config/* /etc/config/
	cp -r /Web_page/RQ/usr/local/bin/* /usr/local/bin/
	cp /Web_page/RQ/root/InterfaceManager/script/* /root/InterfaceManager/script/
	cp /Web_page/RQ/usr/libexec/rpcd/* /usr/libexec/rpcd/
	cp /Web_page/RQ/www/luci2/view/* /www/luci2/view/ 
	cp /www/luci2/view/modemstatus2 /www/luci2/view/diagnostics.modemstatus.js
elif [ "$RK_Product_name" = "RK" ] 
then
	echo "Product_name = RK"
	Product_name="RK"
	cp /Web_page/RK/etc/banner /etc/
	cp /Web_page/RK/etc/config/* /etc/config/
	cp -r /Web_page/RK/usr/local/bin/* /usr/local/bin/
	cp /Web_page/RK/usr/share/rpcd/menu.d/* /usr/share/rpcd/menu.d/
	cp /Web_page/RK/root/InterfaceManager/script/* /root/InterfaceManager/script/
	cp /Web_page/RK/usr/libexec/rpcd/* /usr/libexec/rpcd/
	cp /Web_page/RK/www/luci2/view/* /www/luci2/view/ 
elif [ "$RU_Product_name" = "RU" ] 
then
	echo "Product_name = RU"
	Product_name="RU"
	cp /Web_page/RU/etc/banner /etc/
	cp /Web_page/RU/etc/config/* /etc/config/
	cp -r /Web_page/RU/usr/local/bin/* /usr/local/bin/
	cp /Web_page/RU/usr/share/rpcd/menu.d/* /usr/share/rpcd/menu.d/
	cp /Web_page/RU/root/InterfaceManager/script/* /root/InterfaceManager/script/
	cp /Web_page/RU/usr/libexec/rpcd/* /usr/libexec/rpcd/
	cp /Web_page/RU/www/luci2/view/* /www/luci2/view/ 
elif [ "$RV00_Product_name" = "RV00" ] 
then
	echo "Product_name = RV00"
	Product_name="RV00"
	cp /Web_page/RV00/etc/banner /etc/
	cp /Web_page/RV00/etc/config/* /etc/config/
	cp -r /Web_page/RV00/usr/local/bin/* /usr/local/bin/
	cp /Web_page/RV00/usr/share/rpcd/menu.d/* /usr/share/rpcd/menu.d/
	cp /Web_page/RV00/root/InterfaceManager/script/* /root/InterfaceManager/script/
	cp /Web_page/RV00/usr/libexec/rpcd/* /usr/libexec/rpcd/
	cp /Web_page/RV00/www/luci2/view/* /www/luci2/view/ 
	cp /Web_page/RV00/www/luci2/template/* /www/luci2/template/ 
elif [ "$RV04_Product_name" = "RV04" ] 
then
	echo "Product_name = RV04"
	Product_name="RV04"
	cp /Web_page/RV04/etc/banner /etc/
	cp /Web_page/RV04/etc/config/* /etc/config/
	cp /Web_page/RV04/etc/init.d/* /etc/init.d/
	cp -r /Web_page/RV04/etc/inv_eth/* /etc/inv_eth/
	cp -r /Web_page/RV04/usr/local/bin/* /usr/local/bin/
	cp /Web_page/RV04/usr/share/rpcd/menu.d/* /usr/share/rpcd/menu.d/
	cp /Web_page/RV04/root/InterfaceManager/script/* /root/InterfaceManager/script/
	cp /Web_page/RV04/usr/libexec/rpcd/* /usr/libexec/rpcd/
	cp /Web_page/RV04/www/luci2/view/* /www/luci2/view/ 
	cp /Web_page/RV04/www/luci2/ui.js /www/luci2/
	cp /Web_page/RV04/www/luci2/icons/* /www/luci2/icons/ 
	cp /Web_page/RV04/www/luci2.html /www/
elif [ "$RV54_1_Product_name" = "RV54-1" ] 
then
	echo "Product_name = RV54-1"
	Product_name="RV54-1"
	cp /Web_page/RV54-1/etc/banner /etc/
	cp /Web_page/RV54-1/etc/config/* /etc/config/
	cp -r /Web_page/RV54-1/etc/crontabs /etc/
	cp -r /Web_page/RV54-1/usr/local/bin/* /usr/local/bin/
	cp /Web_page/RV54-1/root/InterfaceManager/script/* /root/InterfaceManager/script/
	cp /Web_page/RV54-1/usr/libexec/rpcd/* /usr/libexec/rpcd/
	cp /Web_page/RV54-1/www/luci2/view/* /www/luci2/view/ 
elif [ "$RV54_2_Product_name" = "RV54-2" ] 
then
	echo "Product_name = RV54-2"
	Product_name="RV54-2"
	cp /Web_page/RV54-2/etc/banner /etc/
	cp /Web_page/RV54-2/etc/config/* /etc/config/
	cp -r /Web_page/RV54-2/etc/crontabs /etc/
	cp -r /Web_page/RV54-2/usr/local/bin/* /usr/local/bin/
	cp /Web_page/RV54-2/root/InterfaceManager/script/* /root/InterfaceManager/script/
	cp /Web_page/RV54-2/usr/libexec/rpcd/* /usr/libexec/rpcd/
	cp /Web_page/RV54-2/www/luci2/view/* /www/luci2/view/ 
elif [ "$RVW50_Product_name" = "RVW50" ] 
then
	echo "Product_name = RVW50"
	Product_name="RVW50"
	cp /Web_page/RVW50/etc/banner /etc/
	cp /Web_page/RVW50/etc/config/* /etc/config/
	cp -r /Web_page/RVW50/usr/local/bin/* /usr/local/bin/
	cp /Web_page/RVW50/usr/share/rpcd/acl.d/* /usr/share/rpcd/acl.d/
	cp /Web_page/RVW50/usr/share/rpcd/menu.d/* /usr/share/rpcd/menu.d/
	cp -r /Web_page/RVW50/root/InterfaceManager/script/* /root/InterfaceManager/script/
	cp /Web_page/RVW50/usr/libexec/rpcd/* /usr/libexec/rpcd/
	cp /Web_page/RVW50/www/luci2/view/* /www/luci2/view/ 
	cp /Web_page/RVW50/www/luci2/template/* /www/luci2/template/ 
elif [ "$RG_Product_name" = "RG" ] 
then
	echo "Product_name = RG"
	Product_name="RG"
	cp /Web_page/RG/etc/banner /etc/
	cp /Web_page/RG/etc/config/* /etc/config/
	cp -r /Web_page/RG/usr/local/bin/* /usr/local/bin/
	cp /Web_page/RG/root/InterfaceManager/script/* /root/InterfaceManager/script/
	cp /Web_page/RG/usr/libexec/rpcd/* /usr/libexec/rpcd/
	cp /Web_page/RG/www/luci2/view/* /www/luci2/view/ 
elif [ "$ID_Product_name" = "ID" ]
then
	echo "Product_name = ID"
	Product_name="ID"
	cp /Web_page/Silbo_IDXX/etc/banner /etc/
	cp /Web_page/Silbo_IDXX/etc/config/* /etc/config/
	cp -r /Web_page/Silbo_IDXX/usr/local/bin/* /usr/local/bin/
	cp /Web_page/Silbo_IDXX/root/InterfaceManager/script/* /root/InterfaceManager/script/
	cp /Web_page/Silbo_IDXX/usr/libexec/rpcd/* /usr/libexec/rpcd/
	cp /Web_page/Silbo_IDXX/www/luci2/view/* /www/luci2/view/ 
	cp /www/luci2/view/modemstatus2 /www/luci2/view/diagnostics.modemstatus.js
elif [ "$RN50_Product_name" = "RN50" ] 
then
	echo "Product_name = RN50"
	Product_name="RN50"
	cp /Web_page/RN50/etc/banner /etc/
	cp /Web_page/RN50/bin/* /bin/
	cp /Web_page/RN50/etc/config/* /etc/config/
	cp -r /Web_page/RN50/etc/inv_eth/* /etc/inv_eth/
	cp -r /Web_page/RN50/etc/nodogsplash/htdocs/* /etc/nodogsplash/htdocs/
	cp -r /Web_page/RN50/usr/local/bin/* /usr/local/bin/
	cp /Web_page/RN50/usr/share/rpcd/acl.d/* /usr/share/rpcd/acl.d/
	cp /Web_page/RN50/usr/share/rpcd/menu.d/* /usr/share/rpcd/menu.d/
	cp -r /Web_page/RN50/root/InterfaceManager/script/* /root/InterfaceManager/script/
	cp /Web_page/RN50/usr/libexec/rpcd/* /usr/libexec/rpcd/
	cp /Web_page/RN50/www/luci2/view/* /www/luci2/view/ 
	cp /Web_page/RN50/www/luci2/template/* /www/luci2/template/ 
else
	Product_name="RK"
	cp /Web_page/RK/etc/banner /etc/
	cp /Web_page/RK/etc/config/* /etc/config/
	cp -r /Web_page/RK/etc/crontabs /etc/
	cp -r /Web_page/RK/usr/local/bin/* /usr/local/bin/
	cp /Web_page/RK/usr/share/rpcd/menu.d/* /usr/share/rpcd/menu.d/
	cp /Web_page/RK/root/InterfaceManager/script/* /root/InterfaceManager/script/
	cp /Web_page/RK/usr/libexec/rpcd/* /usr/libexec/rpcd/
	cp /Web_page/RK/www/luci2/view/* /www/luci2/view/ 
fi
#removed  
rm -rf /Web_page
#cp basic config files to backup config files
cp /etc/config/* /root/InterfaceManager/config/

#Reset and Retain config or incase of updating the firmware
#/usr/local/bin/Testscripts/ReadMacAddr.sh 

serial_num=$(uci get boardconfig.board.serialnum)
Firmwareversion=$(uci get boardconfig.board.FirmwareVer)
Applicationversion=$(uci get boardconfig.board.ApplicationSwVer)
uci set easycwmp.@device[0].serial_number=$serial_num
uci set easycwmp.@device[0].software_version=${Firmwareversion}_${Applicationversion}
uci set remote.tr.ssid=${board_name}_${serial_num}_2G
uci set boardconfig.board.model="$board_name"
uci set boardconfig.board.boardname="$board_name"

device_info="/etc/device_info"

MANUFACTURER=$(grep -w "DEVICE_MANUFACTURER" ${device_info})
MANUFACTURER_Replace="DEVICE_MANUFACTURER=INVENDIS"
sed -i "s/${MANUFACTURER}/${MANUFACTURER_Replace}/" "$device_info"

MANUFACTURER_URL=$(grep -w "DEVICE_MANUFACTURER_URL" "$device_info")
MANUFACTURER_URL_Replace="DEVICE_MANUFACTURER_URL='- SILBO'"
sed -i "s|${MANUFACTURER_URL}|${MANUFACTURER_URL_Replace}|" "$device_info"


DEVICE_PRODUCT=$(grep -w "DEVICE_PRODUCT" ${device_info})        
DEVICE_PRODUCT_Replace="DEVICE_PRODUCT=SILBO-${Product_name}5X"
sed -i "s/${DEVICE_PRODUCT}/${DEVICE_PRODUCT_Replace}/" "$device_info"

uci commit easycwmp
uci commit boardconfig

#Check wifi is there or not.
wifi_enable_disable=$(hexdump -v -n 1 -s 0x61 -e '7/1 "%01X:" 1/1 "%01X"' /dev/mtd2 | sed 's/://g')
wifi_enable_disable=$(echo "$wifi_enable_disable" | tr -d '\013\014\015 ')

#According to device name remove wireless file for RV04-2 and RV04-1 board.
model_path="/tmp/sysinfo/model"
device_name=$(cat "$model_path" | sed 's/Invendis Silbo-//g')

if [ "$device_name" = "RV54-2" ] && [ "$wifi_enable_disable" = "0" ] || [ "$device_name" = "RV54-1" ] && [ "$wifi_enable_disable" = "0" ];then
	rm /etc/config/wireless
fi

#Copy the boardconfig and system in /etc/config path from user data partition
mkdir -p /mnt/image
mount -t vfat /dev/mtdblock7 /mnt/image/
cp /mnt/image/boardconfig /etc/config/ 
cp /mnt/image/system /etc/config/ 
cp /mnt/image/rpcd /etc/config/ 
cp /mnt/image/sysconfig /etc/config/ 
cp /mnt/image/network /etc/config/ 
cp /mnt/image/dhcp /etc/config/ 
#cp /mnt/image/configuration.network.js /www/luci2/view/

umount /dev/mtdblock7

#Run readmacaddr to add macaddr.
if [ "$RN50_Product_name" = "RN50" ];then
	RunReadMacaddr_RN50
else
	RunReadMacaddr
fi

#LOGO
logo_n=$(hexdump -v -n 1 -s 0x60 -e '7/1 "%02X:" 1/1 "%01X"' /dev/mtd2 | sed 's/://g')

if [ "$logo_n" -eq "01" ] || [ "$logo_n" = "FF" ]
then
	echo "Default Silbo Logo"
elif [ "$logo_n" -eq "02" ] 
then
   # Comment out the logo image tag in luci2.html
	echo "Commenting out the logo image tag in luci2.html..."
	sed -i 's|<img src="/luci2/icons/custom_logo.svg" class="logoimg1" />|<!--<img src="/luci2/icons/custom_logo.svg" class="logoimg1" />-->|g' /www/luci2.html

	# Comment out the logo appending line in ui.js
	echo "Commenting out the logo appending line in ui.js..."
	sed -i 's|\.append('\''<img src="/luci2/icons/custom_logo.svg"/>'\'')|//\.append('\''<img src="/luci2/icons/custom_logo.svg"/>'\'')|g' /www/luci2/ui.js                    
	/etc/init.d/uhttpd restart
elif [ "$logo_n" -eq "03" ]
then  
    #mount mtdblock and copy the .svg image to /mnt/image path
	mkdir -p /mnt/image
	mount -t vfat /dev/mtdblock7 /mnt/image/ 
	cp /mnt/image/customconfig /etc/config/
	cp /mnt/image/customconfig /root/InterfaceManager/config/
	Model=$(uci get customconfig.customconfig.CustomModelname)
	uci set system.system.model="$Model"
	uci set boardconfig.board.model="$Model"
	uci set boardconfig.board.boardname="$Model"
	cp /mnt/image/custom_logo.svg /www/luci2/icons/
	manufacturer=$(uci get customconfig.customconfig.manufacturer)
   manufacturer_url=$(uci get customconfig.customconfig.manufacturer_url)
	uci set easycwmp.@device[0].manufacturer=$manufacturer                                     
	device_info="/etc/device_info"

	MANUFACTURER=$(grep -w "DEVICE_MANUFACTURER" ${device_info})        
	MANUFACTURER_Replace="DEVICE_MANUFACTURER=$manufacturer"
	sed -i "s/${MANUFACTURER}/${MANUFACTURER_Replace}/" "$device_info"
	
	MANUFACTURER_URL=$(grep -w "DEVICE_MANUFACTURER_URL" "$device_info")
	MANUFACTURER_URL_Replace="DEVICE_MANUFACTURER_URL=$manufacturer_url"
	sed -i "s|${MANUFACTURER_URL}|${MANUFACTURER_URL_Replace}|" "$device_info"
	
	DEVICE_PRODUCT=$(grep -w "DEVICE_PRODUCT" ${device_info})        
	DEVICE_PRODUCT_Replace="DEVICE_PRODUCT=$Model"
	sed -i "s/${DEVICE_PRODUCT}/${DEVICE_PRODUCT_Replace}/" "$device_info"

	uci commit easycwmp
	/etc/init.d/uhttpd restart 
	umount /dev/mtdblock7
                        
fi

uci commit boardconfig
uci commit system

/etc/init.d/uhttpd restart

/etc/init.d/easycwmp restart

#emptying the file /etc/dnsmasq.conf
echo -n > /etc/dnsmasq.conf 

#To check if the firstboot script got executed.
echo "FirstBootStatus=0" > /etc/FirstBootStatus

exit 0
